### ISSUE TITLE
Odd spacing on lockscreen notification with blank target

### ISSUE THREAD

**Issue by ThatOneCalculator** [KieronQuinn/Smartspacer#101]
### Description

I configured smartspacer to show a blank target only with complications on the lockscreen, which has some odd spacing. Maybe with the blank target, it could use a smaller notification body size?

![Screenshot_20231219-111439](https://github.com/KieronQuinn/Smartspacer/assets/44733677/0e331332-96a3-4515-a9ac-71b2fecb08e4)

**Comment by KieronQuinn** [comment]
This is intentional, the blank target is literally just an empty text one. It's just how it works, the widget and regular Smartspace are the same, it's just less noticeable.

**Comment by ThatOneCalculator** [comment]
Gotcha. On that note though, could there be an "only complications" target for the lockscreen notification that fits into the size of a shrunk notification?

**Comment by KieronQuinn** [comment]
Not really, I suggest you use another Target like the greeting one
