### ISSUE TITLE
[Suggestion] RSS catcher for the extended view

### ISSUE THREAD

**Issue by seadx6-neo** [KieronQuinn/Smartspacer#104]
### Suggestion

Hello, could an RSS catcher be implemented for Smartspacer's full screen (extended view) window be implemented? I have Nova launcher with Smartspacer as my feed and I wish I could add my favorite feeds to still have news but the ones I choose

**Comment by KieronQuinn** [comment]
My current recommendation for this is to use one of the many RSS widgets, it's out of scope for the app at present.

**Comment by seadx6-neo** [comment]
Thanks for at least checking my suggestion

**Comment by nar3n12** [comment]
> Thanks for at least checking my suggestion

Hey, did you find any rss widget? I troed multiple rss apps like nunti, aggregator, feeder, but they don't show up in "add widgets" part in smartspace.

**Comment by seadx6-neo** [comment]
Sadly no

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
