### ISSUE TITLE
[Bug] widget scaling with os size in settings

### ISSUE THREAD

**Issue by Rolodo** [KieronQuinn/Smartspacer#106]
### Description

Not 100% sure if it's related to your all but I'll open an issue in case.
I have my os sizing (scaling) set to the following assuming it start at 0.
Font size 2
Display size 0

And the widget seems to be stretching outside their zone on the lock screen or are misaligned.
Otherwise I'm really happy with the app :)

Thanks

**Comment by KieronQuinn** [comment]
Can you post a screenshot please

**Comment by Rolodo** [comment]
Had to wait for maps to find trafic.

![Screenshot_20231221-194217](https://github.com/KieronQuinn/Smartspacer/assets/46143129/fcd123f2-3290-424a-aea5-c08771bcf062)

Thanks

**Comment by KieronQuinn** [comment]
Yeah that's the system, nothing I can do unfortunately.
