### ISSUE TITLE
2-3 widgets for expanded smartspacer columns

### ISSUE THREAD

**Issue by SeanDylan** [KieronQuinn/Smartspacer#123]
### Suggestion

I've been using smart spacer since release and when i started using expanded smart spacer it's really good but for big screen devices it doesn't make sense to have one widget for every column using two or three widgets for every column is probably good for big devices
![Screenshot_20240103-154604](https://github.com/KieronQuinn/Smartspacer/assets/104182251/c11a623a-a50e-4577-bf84-16011074fedf)
It's pretty weird to look at this in a big screen device

**Comment by KieronQuinn** [comment]
This is out of scope unfortunately, it would open a can of worms around widget scaling and how the grids are handled. I did try it when integrating multiple columns, it broke a ton of stuff and wasn't viable. 

Multi-column is already supported, but it needs to fit two columns of portrait screen width to be enabled. 

In short, Expanded Smartspace is not meant to be a launcher replacement, so things like this are not really a requirement.
