### ISSUE TITLE
[Other] : Enable on Reboot

### ISSUE THREAD

**Issue by niksingh710** [KieronQuinn/Smartspacer#125]
### Issue

I have gone through the [FAQ](https://github.com/KieronQuinn/Smartspacer/blob/main/FAQ.md#q-why-do-i-need-to-reconnect-smartspacer-every-reboot-when-using-native-smartspace) but then also curious if there is any way to get it auto enabled on a rooted device?

**Comment by KieronQuinn** [comment]
It would still have to restart SystemUI, so no. This has been asked before, please search next time.

#91
