### ISSUE TITLE
digital wellbeing entries not correct [Bug] 

### ISSUE THREAD

**Issue by Rausreisser** [KieronQuinn/Smartspacer#126]
### Description

The second and the third entry in the digital wellbeing target is ever equal - ever! (Sorry - my English is not good 😬 and this is my first time I report something in github 🙄 - I hope it's correct this way 🤔)
![Screenshot_2024-01-07-16-33-35-933_com mi android globallauncher](https://github.com/KieronQuinn/Smartspacer/assets/132520478/b293b76b-1a4f-4578-9414-7c9db7665ad1)

**Comment by KieronQuinn** [comment]
Can you add the Google Digital Wellbeing widget to your homescreen, and send a screenshot showing both that and Smartspacer on this target?

**Comment by Rausreisser** [comment]
on a second Handy 📱, the second and the third entry in the digital wellbeing target is also equal, but in reality they are not! (Sorry, my English is not good 😬)
![Screenshot_2024-01-07-16-55-35-60_3822ac0e29cfec8970059bb21d01f05e](https://github.com/KieronQuinn/Smartspacer/assets/132520478/f0ba2a80-0ff5-4654-85ce-57315354ea40)

**Comment by Rausreisser** [comment]
> homescreen

I try....

**Comment by Rausreisser** [comment]
![Screenshot_2024-01-07-17-14-57-66_3822ac0e29cfec8970059bb21d01f05e](https://github.com/KieronQuinn/Smartspacer/assets/132520478/1052ea14-45b5-410f-a778-61366cc48df9)

**This way? **🤔

**Comment by KieronQuinn** [comment]
Which Smartspacer version are you on? This bug was fixed in 1.2.

**Comment by Rausreisser** [comment]
![Screenshot_2024-01-07-17-34-18-04_b59cb6ff56f5ada7a4e76d0e3ae71dc4](https://github.com/KieronQuinn/Smartspacer/assets/132520478/b74ec16a-7999-45c7-8c6c-bfc6a74bc635)

**Comment by Rausreisser** [comment]
On both smartphone 📱

**Comment by KieronQuinn** [comment]
Fixed in 1.6

**Comment by Rausreisser** [comment]
Hello Kieron,
it works fine. Thank you for your support.
