### ISSUE TITLE
Background not cleared when device is unlocked with smartspacer in focus 

### ISSUE THREAD

**Issue by qahameed** [KieronQuinn/Smartspacer#128]
### Description

![Screenshot_20240108-175508](https://github.com/KieronQuinn/Smartspacer/assets/63009570/298868e3-9ab8-4fa2-abe1-6594830f7ab4)
Background shows the main page with app icons when the device is locked and unlocked with smart space was in focus

**Comment by KieronQuinn** [comment]
This is up to the launcher, it's how overlays work. The blur option is meant for this, if it works on your device.
