### ISSUE TITLE
[Suggestion] Hide date at lock screen

### ISSUE THREAD

**Issue by dakirb** [KieronQuinn/Smartspacer#130]
### Suggestion

Having 2 dates are not ideal and don't look nice
It would be ideal if the second date would be invisible or have other information

![Screenshot_20240113-141726](https://github.com/KieronQuinn/Smartspacer/assets/146381023/7a071744-541f-4916-b97d-859abaa8253a)

**Comment by KieronQuinn** [comment]
Add a Target (the blank one if you don't fancy any of the others), this is already possible.
