### ISSUE TITLE
Torch Turn Off Button Not Working

### ISSUE THREAD

**Issue by GiftigSlayer806** [KieronQuinn/Smartspacer#131]
Uploading screen-20240114-011439.mp4…

### Description

When the native smartspace is on the torch turn off button doesn't work and app isn't installed message gets displayed on the bottom of the home screen.The Button works when native smartspace is off but the message is still displayed.

https://github.com/KieronQuinn/Smartspacer/assets/76615830/f3308c1f-0693-4fa1-965b-4563c54ad5d7

**Comment by KieronQuinn** [comment]
This isn't a Smartspacer bug, At a Glance has become disconnected. Switching Native Smartspace off and back on again will fix it. 

The app not installed toast message is an Android bug and was fixed in the last QPR. Your ROM probably needs to update its implementation.
