### ISSUE TITLE
[Bug] Album art picture mismatches with original the ones

### ISSUE THREAD

**Issue by Kiko13bb** [KieronQuinn/Smartspacer#132]
### Description

![Screenshot_20240114-182852_Pixel Launcher](https://github.com/KieronQuinn/Smartspacer/assets/106629760/46002ec7-5127-4e3f-88b2-23b746ef2fa4)
Smartspacer and Spotify

Solution: Stop the song, wait for smartspacer to hide the music's complication, and resume the song to update the album art.
Suggestion: Add a delay before showing the music's complication to match album art.

**Comment by KieronQuinn** [comment]
The album art is sent from the music app. Given Spotify's recent broken changes to how album art is loaded, it is most likely a Spotify bug.
