### ISSUE TITLE
[Bug] Can't resize the widget

### ISSUE THREAD

**Issue by etken4** [KieronQuinn/Smartspacer#134]
### Description

![Screenshot_20240116_193513_One UI Home](https://github.com/KieronQuinn/Smartspacer/assets/133025063/c62fff7f-1424-474e-9613-4564a36dcf2b)

**Comment by KieronQuinn** [comment]
#63 

It's a Samsung bug.

**Comment by MaxOrton** [comment]
found a funny solution:
With the widget on the screen, go to Home up and resize to 4 spaces width. after applying, the widget will take up the width of the screen, then revert to your original (5, 6) and the widget will still take up the entire width.
What's funny is if you will try to add a new smart spacer widget, it will only take up 4 spaces.
