### ISSUE TITLE
Ability to change text align

### ISSUE THREAD

**Issue by auriafoxgirl** [KieronQuinn/Smartspacer#135]
### Suggestion

It would be cool if it would be possible to make a text on widget centered or on right side instead of left, kinda like old google at glance widget
![Screenshot_20240118_220427_Photos](https://github.com/KieronQuinn/Smartspacer/assets/53555592/a307af1c-caad-4e57-ab33-9526fd7a4dc5)

**Comment by KieronQuinn** [comment]
Not possible, the templates do not support this
