### ISSUE TITLE
[Bug] Displaying issue of At a Glance widget

### ISSUE THREAD

**Issue by pokemaster974** [KieronQuinn/Smartspacer#136]
### Description

When choosing Smartspacer for the At a Glance widget, there is a displaying issue. The texts of targets and complications are cutted to their left. There are 2 screenshots of the 2 pages (At a Glance "widget" on the top, normal widget at the bottom).
![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/e13867a1-ab80-4584-8f2b-e7a8fdd8cc9f)

![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/1f0650f2-4928-4ebb-b300-bf6295411e90)

### Setup

Android 14
Smartspacer 1.5.1
Lawnchair 14 Dev #326

**Comment by KieronQuinn** [comment]
I can't reproduce this. Please provide some solid reproduction steps that can actually show the issue happening, screenshots are not sufficient.

**Comment by pokemaster974** [comment]
Hi, this the steps I follow :
1. Install Lawnchair 14 Dev
2. Install Smartspacer
3. Go into Lawnchair settings
4. Go into At a Glance widget settings
5. Choose Smartspacer as provider
6. Go into homescreen

![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/a602a186-c560-41ca-99d3-87a71e34cba3)

**Comment by KieronQuinn** [comment]
I still can't reproduce this. I suspect it might be device specific, some sort of layout issue.
