### ISSUE TITLE
[Bug] Widget At a Glance with Smartspacer as provider could stop to be displayed

### ISSUE THREAD

**Issue by pokemaster974** [KieronQuinn/Smartspacer#137]
### Description
After chossing a different provider for At a Glance into Lawnchair setting, choosing again Smartspacer can't lead to not displaying the At a Glance widget.
The setting :
![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/585f3cc3-eaf1-418e-a6f3-6ca777802e61)

It seems that the authorization request is inconsistent and even after some retries of changing providers I don't receive the request :
![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/a4ff889f-68e3-4287-bc05-4586ce734142)

As soon as the authorization is allowed, it seems that the widget is correctly displaying :
![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/dbc221e3-47e6-45ec-9ff9-7a869c55b14f)

### Setup
Android 14
Smartspacer 1.5.1
Lawnchair 14 Dev #326

**Comment by pokemaster974** [comment]
Update :
In fact, widget At a Glance have stopped to be displayed, even with the authorization allowed and Smartspacer choosen as provider. Normal widget is still displayed.
![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/8e7a9072-e14f-4feb-9e51-38fdbb1cabfc)

![image](https://github.com/KieronQuinn/Smartspacer/assets/28442699/cb0ae0f0-fdce-4009-9966-1d44af9d1029)

**Comment by KieronQuinn** [comment]
Fixed in 1.6
