### ISSUE TITLE
[Bug] no any function takes effect on home.

### ISSUE THREAD

**Issue by sandyfan** [KieronQuinn/Smartspacer#145]
### Description

Smartspacer cannot be set as the default launcher, and of course no functions take effect.
![Screenshot_20240126-181641_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/128270679/57a9bdda-1d2f-4a7b-a087-b0b38123e0ab)
![Screenshot_20240126-181842_Pixel Launcher](https://github.com/KieronQuinn/Smartspacer/assets/128270679/53fa6dbb-8e02-4ef0-ac31-706f07a4c33e)
![Screenshot_20240126-185454_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/128270679/1a3d773f-75fb-40b4-9506-619da8dbe515)
![Screenshot_20240126-185449_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/128270679/a2b3a8b2-1de1-40fd-a499-3dd5fd6d8d97)
as
![Screenshot_20240126-185445_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/128270679/4c1a01ee-1f8e-42f1-9bb4-75a433b3d14f)
As shown in the picture, no new icons or functions appear on the Android desktop.

**Comment by sandyfan** [comment]
![Screenshot_20240126-185658_Permission controller](https://github.com/KieronQuinn/Smartspacer/assets/128270679/b04d29cb-2572-4a22-ad9f-7f9d70f9658a)
My launcher,I installed it by Pixelify Magisk Module.

**Comment by KieronQuinn** [comment]
Both of those Targets are dynamic and appear only as needed. Try adding a static one like Digital Wellbeing and see if it shows up.

**Comment by KieronQuinn** [comment]
No response, assuming that confirmed it was working and closing.
