### ISSUE TITLE
[Suggestion] enhancing FAQ

### ISSUE THREAD

**Issue by Th-o-mas** [KieronQuinn/Smartspacer#148]
### Suggestion

I read the FAQ and one question is not answered. Can I use the App only on Pixel Phones? Or can I use the app on any android deveice (like Samsung phone A54)? 

Can you add question an answer to Faq?

**Comment by KieronQuinn** [comment]
This isn't required, because nowhere does it say that this app is Pixel exclusive, it says **for Android**. The Pixel feature is not mutually exclusive.
