### ISSUE TITLE
Plug in download fail

### ISSUE THREAD

**Issue by Thebear375** [KieronQuinn/Smartspacer#15]
### Description

Maps plug in for smart space continuously fails to download and install. Progressbar stays at 0%. Both on WiFi and data

**Comment by KieronQuinn** [comment]
It works fine for everyone else, you might be being rate limited by GitHub. Download it manually: https://github.com/KieronQuinn/SmartspacerPlugins/releases/download/googlemaps/googlemaps-release.apk
