### ISSUE TITLE
Widgets are misplaced[Bug] 

### ISSUE THREAD

**Issue by ZzzzYyyyO** [KieronQuinn/Smartspacer#150]
### Description

Just like the picture below
![Screenshot_20240201-111914](https://github.com/KieronQuinn/Smartspacer/assets/100761630/53bfd0e7-2847-4afb-8eb7-d6a56cd18625)
Normal situation of widgets
![Screenshot_20240201-112140](https://github.com/KieronQuinn/Smartspacer/assets/100761630/e4a6e95d-a5f4-4e69-bc29-bd4cf845d588)
[smartspacer_target_dump_2024-02-01T11_26_52.761032.txt](https://github.com/KieronQuinn/Smartspacer/files/14119955/smartspacer_target_dump_2024-02-01T11_26_52.761032.txt)

**Comment by KieronQuinn** [comment]
This looks like a temporary rotation-related bug, is this the Discover replacement (overlay)?

**Comment by ZzzzYyyyO** [comment]
> This looks like a temporary rotation-related bug, is this the Discover replacement (overlay)?

Yes,What’s turned on to Replace Google Discover in Smartspaces
![Screenshot_20240201-120133](https://github.com/KieronQuinn/Smartspacer/assets/100761630/8b67d9e2-ac2b-460c-bc6d-3b9061a2b873)

**Comment by KieronQuinn** [comment]
Yeah the overlay does that sometimes. Not something I can fix unfortunately, the window size reporting is the responsibility of the host, which everyone uses an ancient decompiled library from like 7 years ago for. It's a bit buggy.
