### ISSUE TITLE
[Suggestion] Ability to adjust spacing between widgets

### ISSUE THREAD

**Issue by envieme** [KieronQuinn/Smartspacer#152]
### Suggestion

It would be nice to adjust the spacing between widgets placed on smartspacer screen or better ability to overlap widgets. For example the spacing between the weather widgets are too big to my liking and it would nice to add the two clock widgets side by side but cannot be done currently.

![Screenshot_20240201_191121_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/1422393/7ea40186-bb1f-4e95-b021-6b19669b1d82)

**Comment by KieronQuinn** [comment]
#123
