### ISSUE TITLE
[Bug] native smartspace wrong

### ISSUE THREAD

**Issue by sandyfan** [KieronQuinn/Smartspacer#153]
### Description

Before this is ok but now ,look picture..
![Screenshot_20240204-033641_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/128270679/77cddde4-78b2-49d8-860a-7d3fd8610cb8)
I have root access,what about adding root functions to Smart space,by the way.

**Comment by KieronQuinn** [comment]
What device is this, and which ROM are you using if it is custom?

**Comment by KieronQuinn** [comment]
No response again, closing.

This is the second time you've opened an issue with insufficient information and not responded when asked for clarity. If you do it again, I will remove your access to open further issues.
