### ISSUE TITLE
[Other] Samsung S22+

### ISSUE THREAD

**Issue by returntrip** [KieronQuinn/Smartspacer#154]
### Issue

Should I be able to use Native Smartspaces on an S22+? At the moment it is "unavailable". Or should I use OEM Smartspaces?

I have also enabled Enhanced Mode with Shizuku but I cannot see anything on the screen lock, besides Samsung's usual lock screen stuff.

The discovery feed works with Nova's integration tho.

**Comment by KieronQuinn** [comment]
Neither are compatible with Samsung devices. This is working as intended.
