### ISSUE TITLE
Smartspacer doesn't appear in lock screen

### ISSUE THREAD

**Issue by Reiux** [KieronQuinn/Smartspacer#157]
### Description

Hello, Idk if it's my ROM or the app itself but Smartspacer doesn't seem to appear on my lock screen it only shows on Pixel launcher.
![Screenshot_20240206-014928_Pixel Launcher](https://github.com/KieronQuinn/Smartspacer/assets/90865965/f9287f51-6b5b-4af0-96cf-dc8f5d6059ab)
![Screenshot_20240206-014932_Pixel Launcher](https://github.com/KieronQuinn/Smartspacer/assets/90865965/69bbbb63-0bfe-4830-bbb6-4f1e9129ecde)

**Comment by KieronQuinn** [comment]
If it doesn't appear, it's either incompatible with your ROM or you have another mod conflicting with it. There's nothing I can do.
