### ISSUE TITLE
[Bug] Google weather forecast is gone

### ISSUE THREAD

**Issue by srt54558** [KieronQuinn/Smartspacer#159]
### Description

The weather forecast, showing the weather the next hours is gone. I selected it to be showing but it won't display. Is it just my phone or other people's problem too?

I have the Pixel 8 pro, on February update

**Comment by KieronQuinn** [comment]
Which of the weather complications are you using, the At a Glance or Google Weather one?

**Comment by srt54558** [comment]
> Which of the weather complications are you using, the At a Glance or Google Weather one?

The complication

**Comment by KieronQuinn** [comment]
> > Which of the weather complications are you using, the At a Glance or Google Weather one?
> 
> The complication

Yes, I get that. But which one - At a Glance or Google Weather?

**Comment by srt54558** [comment]
> > > Which of the weather complications are you using, the At a Glance or Google Weather one?
> > 
> > The complication
> 
> Yes, I get that. But which one - At a Glance or Google Weather? 

![Screenshot_20240207-070321.png](https://github.com/KieronQuinn/Smartspacer/assets/90862487/557381d3-e457-4cfe-a283-0f2548ad30aa)

This one. Sorry if I'm not really understanding what you mean with that

**Comment by KieronQuinn** [comment]
Please send a screenshot of your complications tab.

**Comment by srt54558** [comment]
> Please send a screenshot of your complications tab. 

![Screenshot_20240207-113624.png](https://github.com/KieronQuinn/Smartspacer/assets/90862487/2b1e2329-80f5-41b8-94c1-66510fbf6d33)


I didn't change anything and the weather forecast is gone

**Comment by KieronQuinn** [comment]
This is caused by one of two things:

- It has disappeared from At a Glance (happens sometimes, only Google can fix it)
- At a Glance has become disconnected. Disabling/enabling Native Smartspace will fix it, or rebooting.
