### ISSUE TITLE
[Suggestion] Tile for opening an app

### ISSUE THREAD

**Issue by srt54558** [KieronQuinn/Smartspacer#164]
### Suggestion

Hello!
Id really love to set a tile, that looks like the music widget, with the app icon and app name. When the tile is clicked, it opens the app (but if its clicked on lockscreen, obviously the screen user is asked to unlock the screen). Would this be possible?
Greetings

**Comment by KieronQuinn** [comment]
Please read the message you get when making an issue, plugin suggestions go on https://github.com/KieronQuinn/SmartspacerPlugins/issues
