### ISSUE TITLE
Widget keeps disappearing

### ISSUE THREAD

**Issue by jameil** [KieronQuinn/Smartspacer#166]
### Description

Widget from Home Agenda-Calendar Widget keeps disappearing. It reapers after resizing. But disappears again when smartspacer reloads.

**Comment by KieronQuinn** [comment]
When it reappears, are you readding it or does it reappear by itself?

**Comment by jameil** [comment]
> When it reappears, are you readding it or does it reappear by itself?

It reappears by itself. I have to change the widget height, for example change the height to 4 and back to 3 and it reappears.

**Comment by KieronQuinn** [comment]
It's the widget issue mentioned in the picker then. Nothing I can do.

**Comment by KieronQuinn** [comment]
I am actively monitoring the widget problem though, there's a few apps with this issue and Google's response thus far ("base your launcher on launcher3") has been absolutely useless. Hopefully myself or someone else is able to crack it at some point so we can get widgets working without having to include an entire launcher codebase.
