### ISSUE TITLE
[Bug] Widget height is not recognized correctly

### ISSUE THREAD

**Issue by atuy1219** [KieronQuinn/Smartspacer#172]
### Description

![Screenshot_20240314-005709](https://github.com/KieronQuinn/Smartspacer/assets/130917473/494cd008-133d-413a-bdc0-d28cd204750b)
![Screenshot_20240314-005711](https://github.com/KieronQuinn/Smartspacer/assets/130917473/90ca85ee-7ae7-4ead-a413-2ddfd4d3ed66)

Even though the Google Calendar widget is tall enough, the schedule is displayed as if the height is short.

**Comment by atuy1219** [comment]
Operating environment
Android14QPR2 Pixel6a
Lawnchair14 dev

**Comment by atuy1219** [comment]
![Screenshot_20240321-145809](https://github.com/KieronQuinn/Smartspacer/assets/130917473/93dfd1dd-df79-4de9-b7b5-25d673b6f0ea)
It works fine if it's oriented sideways.

**Comment by KieronQuinn** [comment]
This should be sorted with the widget changes in 1.7, let me know if not

**Comment by atuy1219** [comment]
Thank you very much!
