### ISSUE TITLE
[Suggestion]  Install the plugins automatically in background

### ISSUE THREAD

**Issue by DreadedLama** [KieronQuinn/Smartspacer#175]
### Suggestion

Given that Smartspacer already possesses Shizuku access, the plugins can be installed automatically in the background without requiring manual permission to install each time.

**Comment by KieronQuinn** [comment]
This won't be done for a couple of reasons:
- Shizuku access is only available with enhanced mode enabled, which would mean maintaining two separate paths for this feature
- Showing the package installer is a layer of transparency when installing plugins from the repository, which theoretically may be malicious. The repository has a report system for this, but it's all manual - if someone were to compromise wherever the APK is hosted and replace it, showing the package manager would still show the name & icon of the plugin being installed, which makes it impossible to replace the plugin with an app with a different name.
