### ISSUE TITLE
[Bug] quick tile rearrange option goes hidden 

### ISSUE THREAD

**Issue by nx-smul** [KieronQuinn/Smartspacer#177]
### Description

Quick tile rearrange option a pencil goes hidden after applying smartspacer also add a option to adjist delay of showing tiles some tiles stays in the space for too long like google finance

**Comment by KieronQuinn** [comment]
I don't understand, post a screenshot or ideally a screen recording please

**Comment by KieronQuinn** [comment]
No response, closing
