### ISSUE TITLE
Show Google Tasks please

### ISSUE THREAD

**Issue by chjohans** [KieronQuinn/Smartspacer#178]
### Suggestion

Showing calendar events from my GOogle calendar works great, but I'm also using tasks quite extensively. Either due on a spesific date or at a spesific time of a spesific date. Currently I don't see any option to show such tasks.

It would be great to get that option, with a confugurable option to show overdue tasks on each current day just like Google calendar does.

In google Calendar you can choose "Tasks" among al lthe other "calendars" to show, it would probably? be possible to let us chose "tasks" in "Settings" in the current Calendar Target.

**Comment by KieronQuinn** [comment]
You can already show upcoming tasks by adding a Notification Target and setting it to Google Tasks. The calendar system in Android does not support tasks like it does calendar events, so showing tasks that aren't upcoming would need to be a plugin.
