### ISSUE TITLE
[Suggestion] Option to show targets AFTER complications in extended smartspace

### ISSUE THREAD

**Issue by victor-marino** [KieronQuinn/Smartspacer#179]
### Suggestion

Hi there.

First of all, thanks so much for this amazing piece of software :-)

Right now, it seems like whenever any targets are active, they will always show at the top of the extended smartspace, before any of the "static" complications. We can rearrange the order of individual items inside the targets block, and individual items inside the complications block. But unless I'm missing something there's no way to show the targets block after the complications block, am I right?

Would it be possible to offer an option to swap them around?

Because complications are static and tend to be just a small widget, I'd prefer to see them always on top. Whereas targets are dynamic and always changing in both content and size, requiring scrolling, so I'd prefer them to stack below the targets.

I think it would be great to have the option to swap them around at least.

**Comment by KieronQuinn** [comment]
Added in 1.7

**Comment by victor-marino** [comment]
Thanks so much, that was fast!

Could the same thing be done for the regular widgets that are added to the extended smartspace? So that we can have our regular widgets pinned on top, then everything else below?

**Comment by KieronQuinn** [comment]
> Thanks so much, that was fast!
> 
> Could the same thing be done for the regular widgets that are added to the extended smartspace? So that we can have our regular widgets pinned on top, then everything else below?

Probably not as it would likely cause confusion with the rearrange system.
