### ISSUE TITLE
[Suggestion] Run without accessibility

### ISSUE THREAD

**Issue by yukikwi** [KieronQuinn/Smartspacer#18]
### Suggestion

Some banking apps don't allow third-party apps to use accessibility. Maybe adding the option to run smartspacer without accessibility is a good idea.

![Screenshot_20231026_085157_Google](https://github.com/KieronQuinn/Smartspacer/assets/66879660/f14d7ef4-71f6-42e0-8d2f-5f56743b1b05)

**Comment by KieronQuinn** [comment]
The widget relies on accessibility. If you use a different method, like a launcher with Smartspacer built in, or Native Smartspace, it is not required. Otherwise, this is not possible.

**Comment by Snowworm3000** [comment]
Perhaps this could work as a solution. Run this command on a PC (or terminal emulator if rooted):

`adb shell pm install -i "com.android.vending" -r /sdcard/[path to APK])`
This will trick the banking app into believing Smartspacer was installed via the Google Play store.

**Comment by KieronQuinn** [comment]
It's not checking who installed Smartspacer. It's checking if Accessibility is enabled, which it is. There's no fix for this unfortunately.

**Comment by Jnss98b** [comment]
I'd complain to your bank low key. Blocking you out bc of accessibility service usage is a scummy move
