### ISSUE TITLE
[Suggestion] Allow disabling shadow in Expanded Smartspace

### ISSUE THREAD

**Issue by Username1-a** [KieronQuinn/Smartspacer#183]
### Suggestion

Hi, it's great that you've added an option to disable widget's text shadow on a standalone widget in a recent update, but the problem is that the shadow still persists when Smartspacer is used as At a Glance provider in Lawnchair launcher (version 14 Beta 2) 
With shadow it just looks kinda blurry with a dark text and on a light wallpaper – hope it somehow could be fixed on your end

Good luck

Comparison:
![Screenshot_20240407-000033_Lawnchair~2](https://github.com/KieronQuinn/Smartspacer/assets/47947180/43629847-9e82-4124-9816-2769ccf2f375)

Smartspacer on Android 13 lockscreen seems to be fine (no shadow):
![Screenshot_20240407-000056_Chrome~2](https://github.com/KieronQuinn/Smartspacer/assets/47947180/0ba5adcb-31b6-4fc0-bafc-acc5456b373e)

P.S. Widget's text shadow also seems to persist in Expanded Smartspacer

**Comment by KieronQuinn** [comment]
Yes, this should be possible as an option and adding it to Expanded Smartspace will also allow Lawnchair to add an option to do that (although their implementation is no longer under my control)

**Comment by KieronQuinn** [comment]
The behaviour in 1.7.1 now matches the rest of the app (shadow on white, not on black text). There's an option to disable shadows entirely on Expanded Smartspace too, as well as an option for developers using the SDK to call to disable them too - but like I say, I have no control over whether anyone implements that.
