### ISSUE TITLE
[Suggestion] Other Target Shown Requirement

### ISSUE THREAD

**Issue by Carson365** [KieronQuinn/Smartspacer#184]
### Suggestion

Suggestion: Allow checking whether another target is shown as a condition to show a target (with the option to invert it)

Ex. I would like to have both Music and Now Playing targets shown, but not both at the same time.

The optimal fix for this in my opinion would be an option to only show Now Playing if Music is not already shown (and more generally allow this sort of filter for all targets/complications)

**Comment by KieronQuinn** [comment]
This has been suggested a few times and currently it's not going to happen due to the potential for feedback loops it would cause. It would mean writing an entire system for knowing which Targets & Complications are linked to which, detecting trying to link two which already impact each other and preventing that. 

In short, way too much hassle for what is quite a niche suggestion.

**Comment by Carson365** [comment]
Not going to push the issue further than this, just hoping you might reconsider if there was a possibility for a simple(r) implementation.

A feedback loop could be prevented by triggering the target regardless, and instead just avoid showing it.

(i.e.
A is triggered, but shown only if B is not triggered.
B is triggered, but shown only if A is not triggered.
Since both were triggered, neither A nor B are shown.)

It would result in less complicated and non-cascading behavior which may not be desirable for every niche case, but should satisfy most of the more basic ones like mine.

Otherwise a way to make some sort of target "group" where only the first n number of active targets is shown would also do the job.

Thank you!

**Comment by KieronQuinn** [comment]
I think it's easier if for each case like this a requirement that isn't based on other Targets or Complications is better, for example in your case you could use Tasker to  make a requirement to only show Now Playing when music is not playing ([see this](https://www.reddit.com/r/tasker/comments/14nti90), invert that as a requirement)

A dynamic Target or Complication almost always has a trigger that can be used to create a requirement too, without having to introduce complex detection methods or grouping to prevent the app falling over.

**Comment by Carson365** [comment]
Quite reasonable. I'm using MacroDroid which looks to also be supported by the tasker plugin, so that will certainly be an option for me. 

Since that opens up several possibilities, and puts the burden for ensuring compatibility on the user, would it be possible to open up "target visibility" as a trigger to the tasker plugin? It would allow the precise logic I'm looking for without the inconsistency of ensuring the triggers that SmartSpacer uses to show complications coincides with the triggers I set up in MacroDroid to hide them.

Regardless, I'm very happy with the Tasker plugin as an adequate solution and very glad you mentioned it and took the time to help me out. Thanks again!
