### ISSUE TITLE
[Suggestion] Add Configure widget section in Smartpacer settings 

### ISSUE THREAD

**Issue by ujwal246** [KieronQuinn/Smartspacer#188]
### Suggestion

On selecting Smartpacer on Lawnchair 14 at a glance, long pressing at a glance takes to smartpacer settings where there is no option to customise padding.
There is option of configure widget on Smartpacer separate widget.
![Screenshot_20240409_100155_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/117264003/8db4a75c-46b7-4b12-bb74-44cb93a22095)
![Screenshot_20240409_095914_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/117264003/1c2e3c9f-48d1-4c14-830f-ea22412a7a60)

**Comment by KieronQuinn** [comment]
This is the responsibility of Lawnchair, not Smartspacer. Their implementation is using the SDK, its padding and other options are not under my control.
