### ISSUE TITLE
Not working properly at all

### ISSUE THREAD

**Issue by Upapalmtree** [KieronQuinn/Smartspacer#189]
### Description

I have a pixel 7, installed as instructed.  Added complications and target plugins. App has no scrolling ability? Is not showing any targets or complications I've loaded, except for countdown timer.  Can't see where to order the plugins in my preference? Help please!

**Comment by KieronQuinn** [comment]
Please post screenshots of your added Targets & Complications and I can advise. Also please say if you're using the widget, Native Smartspace or a launcher which has Smartspacer support (like Lawnchair)

**Comment by Upapalmtree** [comment]
Hi, screenshots enclosed for you.  I'm using the current Nova launcher.
One thing is that the shizuku app won't stay connected, wireless debugging
keeps stopping, and once I set shizuku , pair it, andd start it, within 10
minutes it says 'shizuku pairing failed cannot connect to wireless
services'.
Hope you can help.  Have enclosed a screenshot of my homepage showing the
app with arrows rather than scrolling across.

**Comment by KieronQuinn** [comment]
I don't see any screenshots, please try attaching them to the GitHub issue rather than replying to the email.

The widget cannot scroll horizontally, that is a limitation of Android and is made clear in the app. The page arrows are provided instead.

**Comment by KieronQuinn** [comment]
No response, closing
