### ISSUE TITLE
[Suggestion] Add Force single target a line option 

### ISSUE THREAD

**Issue by Left024** [KieronQuinn/Smartspacer#19]
### Suggestion

When I use aftership , everything is fine
![Screenshot_20231026-202007_Mosaic_20_27_1](https://github.com/KieronQuinn/Smartspacer/assets/20574903/88267970-c40f-4dfc-9094-e5a544db19a2)
But sometimes the aftership won't load map or image, then it will look like this
![Screenshot_20231026-202040_Mosaic_20_27_15_1](https://github.com/KieronQuinn/Smartspacer/assets/20574903/d88bb733-f24a-4b01-9533-7d1ea42f9b03)
Which is not that beautiful

So if there is a option can let aftership or other targets show only a line, it will be great.

**Comment by KieronQuinn** [comment]
Wrong repository, aftership plugin issues go to https://github.com/KieronQuinn/SmartspacerPlugins/issues

Please read the message in the issue creation form next time.
