### ISSUE TITLE
[Suggestion] Data usage per day

### ISSUE THREAD

**Issue by ujwal246** [KieronQuinn/Smartspacer#190]
### Suggestion

Add option data usage of a day.
This is important for Mobile data users to track data used in a day.
Many OEMs have this feature on quick panel but absent in one ui.
Please add.

**Comment by KieronQuinn** [comment]
Feature requests for plugins go on the [Smartspacer Plugins](https://github.com/KieronQuinn/SmartspacerPlugins) repository, but this has already been requested there so please don't make another issue 

Please also read the message when creating an issue next time which clearly states this.
