### ISSUE TITLE
1.7.0 and 1.7.1 crashes down Hyperos home launcher when adding widget to home screen 

### ISSUE THREAD

**Issue by MSAnwr95** [KieronQuinn/Smartspacer#191]
### Description

As the title suggest, 1.7.0 and 1.7.1 updates crashes Hyperos home launcher whenever I try to re add a new widget. When crashes, no widget being added. The one I added from older version (1.6.4) still works fine, even after I updated it to 1.7.0 and 1.7.1
Here's the log from xiaomi bug report side:
![Screenshot_2024-04-12-20-34-56-823_com miui bugreport-edit](https://github.com/KieronQuinn/Smartspacer/assets/113194120/c155a161-bcac-4b5f-8e48-5ef6e67d77b4)

Device information: Redmi note 12 4g
OS: Hyperos 1.0.2.0.

The app still works fine with other launchers.
Let me know if you need the smartspace dump log.

**Comment by KieronQuinn** [comment]
Should be fixed in 1.7.2
