### ISSUE TITLE
[Bug] Expanded smartspacer margins reduced

### ISSUE THREAD

**Issue by jameil** [KieronQuinn/Smartspacer#194]
### Description

The margins in expanded smartspacer have reduced in the recent update. Previously, it used to be almost the width of the screen.
![Screenshot_20240417-005710](https://github.com/KieronQuinn/Smartspacer/assets/36410267/edf9a312-e089-446b-93a6-d5db31b83459)

**Comment by KieronQuinn** [comment]
This is intentional, it's how the grid system was implemented.

**Comment by jameil** [comment]
Okay, any way to make it fill the full width?

**Comment by KieronQuinn** [comment]
Only by adjusting your DPI
