### ISSUE TITLE
[Suggestion] Current song status (Now Playing)

### ISSUE THREAD

**Issue by ujwal246** [KieronQuinn/Smartspacer#195]
### Suggestion

![Screenshot_20240408_143548_Lawnchair](https://github.com/KieronQuinn/Smartspacer/assets/117264003/1fa1f934-cf7b-4ef2-b6c2-91caed095994)
Add border around cover to keep track of song status.

Here I used At a glance kwgt by teamfiles.

**Comment by KieronQuinn** [comment]
This would cause significant battery drain and performance issues with having to re-render an image at least once a second for it to be usable unfortunately.

**Comment by ujwal246** [comment]
You can add option for those who want with battery drain warning.

**Comment by KieronQuinn** [comment]
Sorry, no I draw the line at this. Re-rendering a full bitmap image every second for the purpose of showing a progress bar is madness. Not even worth the effort of implementing.
