### ISSUE TITLE
[Bug] Overflow on small device (using lawnchair)

### ISSUE THREAD

**Issue by MrDodojo** [KieronQuinn/Smartspacer#200]
### Description

Using smartspace as a provider for at a glance in lawnchair makes it overflow on my device
![Screenshot_20240428-135851](https://github.com/KieronQuinn/Smartspacer/assets/47711280/8338adee-f413-433b-8640-a5130b1599c8)
The device I am using is a unihertz jelly star, which is a small phone, so the _smallest width_ developer setting is set at 320dp(so things are still visible) Other at a glance providers like Google widget work. 
![Screenshot_20240428-140105](https://github.com/KieronQuinn/Smartspacer/assets/47711280/8597a8c4-d714-4c47-8c8c-14eca14e977e)
When the smallest width is set to e.g. 360, the smartspace at a glance widget does not overflow anymore, but is not desirable.
![Screenshot_20240428-140407](https://github.com/KieronQuinn/Smartspacer/assets/47711280/773f0c7e-c6e4-4a08-9a7d-1145803a9756)
Don't know which of the projects this is best reported to.

**Comment by KieronQuinn** [comment]
This is a Lawnchair bug and an issue already exists on their repository to fix it. It's not under my control.
