### ISSUE TITLE
Compatibility with Pixel Launcher Mods, search bar replacement

### ISSUE THREAD

**Issue by sameerasw** [KieronQuinn/Smartspacer#201]
### Suggestion

It would be great to be able to move the at a glance widget to the Pixel Launcher's search bar area so content is present only in the bottom area when the at a glance widget is also hidden.

Currently, the SmartSpacer widget can not be added as a search bar replacement probably because the settings page for the widget appears before creating the widget itself. Nit sure what the exact issue but this combination would be awesome.

Thanks <3

**Comment by sameerasw** [comment]
https://github.com/KieronQuinn/Smartspacer/assets/68902530/edc209b8-2895-4c71-9cb3-ba9e52b54d8e

**Comment by KieronQuinn** [comment]
This was a Pixel Launcher Mods bug, fixed in the latest update.
