### ISSUE TITLE
It is showing weather icon two times and not showing todays date it was fine yesterday but today when I see it looks , Today 41/27 ~Haze~27, No date has been written here only weather forcast[Bug] 

### ISSUE THREAD

**Issue by Narutoindia** [KieronQuinn/Smartspacer#202]
### Description

It is showing weather icon two times and not showing todays date it was fine yesterday but today when I see it looks , Today 41/27 ~Haze~27, No date has been written here only weather forcast 
![Screenshot_20240504_071404_One UI Home](https://github.com/KieronQuinn/Smartspacer/assets/97081100/b88bf9f0-a966-4ddf-83c9-ab9ec3f07fd7)
[Bug]

**Comment by KieronQuinn** [comment]
This is normal, that is the weather forecast from At a Glance. It is not part of Smartspacer.
