### ISSUE TITLE
Resize and overlap widgets in expanded smartspace

### ISSUE THREAD

**Issue by Shubhamkr4** [KieronQuinn/Smartspacer#204]
### Suggestion

Just like we normally resize and overlap widgets on home screen, it will be real good if we can do it...by default a widgets takes one whole line for itself in expanded smartspace which doesn't look good at all

Thanks for you precious time

**Comment by KieronQuinn** [comment]
Smartspacer is not a launcher replacement and this verges into the realm of custom launchers. It's also not supported by the current layout system, so I won't be adding this, sorry.
