### ISSUE TITLE
[Bug] Album art isn't square

### ISSUE THREAD

**Issue by NikunjKhangwal** [KieronQuinn/Smartspacer#206]
### Description

When choosing square album art, the art doesn't become a correct square. (The dimensions are supposed to be equal) It's still a rectangle with less length and same width. I'm not sure if this is actually a bug because the app says "attempt" to make a square. Feel free to close it if irrelevant.

![IMG_20240516_093815](https://github.com/KieronQuinn/Smartspacer/assets/99175083/71e36ee5-6c92-4424-93d1-a7cf9712b367)

**Comment by KieronQuinn** [comment]
Not a bug, this is intentional and there's an option to make it square in the settings if supported.

**Comment by NikunjKhangwal** [comment]
I'm actually talking about that setting to make it square. The screenshot is after enabling it. It's still not a square.

**Comment by KieronQuinn** [comment]
It's not supported on your device then. That setting only works where it's possible.

**Comment by NikunjKhangwal** [comment]
Ok. Thanks
