### ISSUE TITLE
[Bug] spotify now playing disappears after some time

### ISSUE THREAD

**Issue by Shubhamkr4** [KieronQuinn/Smartspacer#211]
### Description

Spotify now playing disappears after 5-10 secs of playing while audio is still playing, sometimes it even disappeares when I started playing a song and as soon as I minimize spotify...I could see that at a glance is showing that song but for just a sec and it disappears.

The lawnchair at a glance works perfectly fine, its just the issue with smartspacer one.

**Comment by KieronQuinn** [comment]
Music updates come from the system, it's out of my control.
