### ISSUE TITLE
Now Playing (Ambient Music Mod) Not showing on the widget [Bug] 

### ISSUE THREAD

**Issue by mcspidey95** [KieronQuinn/Smartspacer#212]
### Description

![Screenshot_20240530_114922](https://github.com/KieronQuinn/Smartspacer/assets/90018162/0e2f6e83-1b89-4802-85e4-b012b40c1bd3)

it worked initially, but now as you can see in the screenshot, ambient music mod detected a song, but it's not being displayed on the widget. Ive given smartspacer every single permission it needs and also disabled battery optimization for it.

**Comment by KieronQuinn** [comment]
Do the song recognitions appear in the notification shade?

**Comment by mcspidey95** [comment]
Nope. The recognitions appear nowhere, not even on the extended smartspace. The only place the recognitions appear are on the music mode widget, and inside the app

**Comment by KieronQuinn** [comment]
If there's no notification then this isn't a Smartspacer issue, since it relies on the notification. However, I can't reproduce this in Ambient Music Mod either. Make sure you've not got the notification disabled, and try reinstalling AMM.

**Comment by mcspidey95** [comment]
yeah, that was the issue. Got it working now. For some reason that option wasnt there in the notification settings at all, had to reinstall the app to find it. Its working now, so thanks man.
