### ISSUE TITLE
[Suggestion] Add an alternative way to remove widgets from Expanded view

### ISSUE THREAD

**Issue by lucasdeeiroz** [KieronQuinn/Smartspacer#213]
### Suggestion

I have one widget from Samsung (Battery Status - circle) that is impossible to remove from Smartspace Expanded mode. If long pressed, the buttons get in the way and the remove/reorder/options menu is not shown.
Suggestion 1: make an alternative way to remove widgets alongside the 'Add' button, allowing the user to select the widget to be removed.
Suggestion 2: make an alternative way to remove widgets inside the reorder page. This one I don't like so much because in my example, I could only enter the reorder page through another widget that allows me to open the reorder/remove/options menu.

**Comment by KieronQuinn** [comment]
I'm not sure what you mean by the buttons getting in the way, there should be no other buttons. Can you send a screenshot or a screen recording?

**Comment by lucasdeeiroz** [comment]
https://github.com/KieronQuinn/Smartspacer/assets/18245855/94f9fd19-5d5b-486c-9e40-40edb127057e

Of course.
The button that gets in the way is from the widget itself. I noticed that happens on other widgets as well (Google Calendar is one example), but Battery Status is the only one that this behaviour prevents the menu from opening anywhere in the widget area.
In the video, I show the menu opening in YouTube Music and Beeper widgets, but not in Battery Status widget.

**Comment by KieronQuinn** [comment]
Oh that's what you mean. You can long press outside of the widget area to open the menu, the long press listener's box is always larger than the widget.

**Comment by lucasdeeiroz** [comment]
https://github.com/KieronQuinn/Smartspacer/assets/18245855/1118cdae-80a5-4e16-98ab-d979e488c3fe

Embarrassing... I have been trying this for a long time, never was able to open the menu. But I mean, it was still hard to open it, as you can see.
Although my issue is fixed, I think it's worth a thought on it.

Thank you very much!

**Comment by KieronQuinn** [comment]
It's been raised a few times, there isn't really an ideal possible solution - in an ideal world, the long click listener would work on all the widgets, but it gets overridden by some widgets and I'm not sure why. I'll take another look into it.

**Comment by MRDGH2821** [comment]
I'm using Nova launcher in which I enabled smartspacer.
And I'm unable to resize nor remove the google calendar widget. I can remove/resize others just fine, but Gcal, no matter wherever I long press, options don't popup

**Comment by KieronQuinn** [comment]
1.7.5 improves on this, Google Calendar widget seems pretty reliable to be long pressed now.
