### ISSUE TITLE
[Bug] first complication is always shown next to date

### ISSUE THREAD

**Issue by AllesMeins** [KieronQuinn/Smartspacer#216]
### Description

I'm new to Smartspacer so I'm not entirely sure if this is a bug or I'm just to stupid to properly use it. So sorry if it is the latter.

I want to build a very minimalistic smartspace without any date. But it seems no matter what I do, as soon as I add complications the first one is always shown next to the date. Additionally: Some targets are not shown if I have only one complication.

What I did:

1. Remove all targets and complications
2. Create a target of type blank or greeting 
3. Create one complication (e.g. WhatsApp count or K-9 count)

What happens:
The complication is shown next to the current date. The target (if I used greeting) is not shown at all. Only if I add a second complication the target is shown with the second complication below it. 

What I expected: 
The target should be displayed together with the complication. No date should be displayed.

**Comment by KieronQuinn** [comment]
Send a screenshot please

**Comment by AllesMeins** [comment]
Sorry, what I forgot to mention is that this happens only on the lockscreen. On the homescreen it works fine. So here are some screenshots. This is my current setup:

![Screenshot_20240617-230401](https://github.com/KieronQuinn/Smartspacer/assets/2261844/8208c83d-546a-4da4-819c-eeefe925d537)
![Screenshot_20240617-230355](https://github.com/KieronQuinn/Smartspacer/assets/2261844/6d43f1c6-1bf6-41b6-9d10-34c005e2f642)

And this is what I get on the lockscreen:
![Screenshot_One_Complication](https://github.com/KieronQuinn/Smartspacer/assets/2261844/4d1b89ac-1d4f-47c0-a3e5-20eab2871dd8)

And here is how it looks, when I add a second complication. Now the target, that was missing before, is displayed.

![Screenshot_Two_Complications](https://github.com/KieronQuinn/Smartspacer/assets/2261844/c4f8d034-ecac-4729-90eb-fc27967cc4cf)

**Comment by KieronQuinn** [comment]
That is Split Smartspace, it's normal.

**Comment by AllesMeins** [comment]
Thanks for clearing that up for me. Is there a way to turn it off so that it shows the target I defined instead of the date, when I've only on complication?

**Comment by KieronQuinn** [comment]
No, the date isn't controlled by Smartspace so can't be disabled.

**Comment by AllesMeins** [comment]
Oh, that's too bad. Than I'll have to find some way around it. Thanks for your quick help.
