### ISSUE TITLE
[Suggestion] Show notification groups in settings

### ISSUE THREAD

**Issue by AllesMeins** [KieronQuinn/Smartspacer#218]
### Suggestion

Most apps put their notifications not only in different channels but they are also grouped. It would be helpful to show these groups when creating a notification target.

For example: K-9 mail adds a group for every mail account and than similar channels under this group. In the notification settings it looks something like this: 

account1@domain.com
- Messages
- Miscellaneous

account2@domain.com
- Messages
- Miscellaneous

When setting up a target in smartspacer I can't see those groups. So I end up with a bunch of channels all named "Messages" or "Miscellaneous" and I need to guess which channel belongs to which mail account.

**Comment by KieronQuinn** [comment]
Added in 1.7.5
