### ISSUE TITLE
[Bug] Some issues with Android 15

### ISSUE THREAD

**Issue by atuy1219** [KieronQuinn/Smartspacer#221]
### Description

I am currently running Android 15 and have encountered the following issues after updating the app to version 1.7.5:

1. Text overlaps the navigation bar.
2. Unable to tap on widgets when using Expanded Smartspace.

Android15 beta3,Pixel6a, lawnchair by goooler

**Comment by KieronQuinn** [comment]
Which screen are you seeing text overlapping on?

**Comment by atuy1219** [comment]
https://github.com/KieronQuinn/Smartspacer/assets/130917473/738e6e0f-5892-406a-8bde-e9072ab1f0e7

![Screenshot_20240621-085500](https://github.com/KieronQuinn/Smartspacer/assets/130917473/1078fbea-9ba5-4ed6-a753-f4bf538ea919)

Here is the image.

Also, I discovered that widgets can only be tapped when returning from the widget selection screen.(Refer to the video)

**Comment by KieronQuinn** [comment]
Yes, it appears Android 15 is stricter at blocking background starts than 14 was, although it may just be complaining about a method call that isn't needed. I'll get it sorted.

**Comment by KieronQuinn** [comment]
Both fixed in 1.7.6
