### ISSUE TITLE
[Bug] Smartspacer at glance provider limited to 5 pages/targets

### ISSUE THREAD

**Issue by pogman-code** [KieronQuinn/Smartspacer#224]
### Description

If Smartspacer has more than 5 target, only the first 5 are show in the "At a Glance" widget.

NB: At first I thought this was a Lawn chair issue but it seems that it wasn't (see https://github.com/LawnchairLauncher/lawnchair/issues/4328)

### Steps to reproduce

1. Install Smartspacer
2. Add more than 5 targets to Smartspacer
3. Go to Lawnchair Settings
4. Click on At A Glance
5. Change provider to Smartspacer
6. Go back to home screen
7. Only the 5 first smartspacer target are shown

### Expected behavior

All Smartspacer targets should be show in "At a Glance" widget.

### Device information

- Device: Xiaomi Mi 10 Lite 5G (Monet)
- OS: LineageOS 19.1
- App version: 1.7.6

**Comment by KieronQuinn** [comment]
This is now handed over to the Lawnchair team as the SDK exposes the config to be overridden. I can't do anything more.

**Comment by pogman-code** [comment]
Sounds perfect, thanks!
