### ISSUE TITLE
Add vertical alignment layout

### ISSUE THREAD

**Issue by makerandreas** [KieronQuinn/Smartspacer#227]
### Suggestion

I have a suggestion. How about adding an option to change the widget alignment display to 2 options: left alignment (default), and center alignment (just like the old version of the Google At a Glance widget, which displays the target and one of the complications that we can set). I hope you understand what I mean.

**Comment by KieronQuinn** [comment]
The 'centered' alignment style would not work with the various templates, so this is not viable.
