### ISSUE TITLE
[Suggestion] Widget background

### ISSUE THREAD

**Issue by leifalbor** [KieronQuinn/Smartspacer#230]
### Suggestion

Is there any chance of adding opaque and/or translucent widget backgrounds? Full transparency makes it difficult to read widget content on numerous wallpapers.

**Comment by KieronQuinn** [comment]
If you are able to, can you send a screenshot of what it looks like currently

**Comment by KieronQuinn** [comment]
I've investigated this and it's simply not enough space for there to be a background while maintaining a top/bottom margin that makes it not look terrible. I suggest using the option to change the text colour to fix the contrast.
