### ISSUE TITLE
[Bug] Unable to resize Smartspacer widget on One UI Home

### ISSUE THREAD

**Issue by eyalm2000** [KieronQuinn/Smartspacer#232]
### Description

https://github.com/KieronQuinn/Smartspacer/assets/141010573/990e73c8-b707-4988-acc7-3b39a63428e2

I am unable to resize the Smartspacer widget's width on One UI Home. I can resize it vertically, but not horizontally. 
In the attached video, you can see that I can resize other widgets, but not the Smartspacer widget's width.

**Comment by KieronQuinn** [comment]
#63
