### ISSUE TITLE
[Bug] "Music" relaunches music app on each tap 

### ISSUE THREAD

**Issue by mario-g98** [KieronQuinn/Smartspacer#235]
### Description

I am not sure about the terminology, but when I tap on music target, it opens the player as it has been force closed, instead of showing the last state in which the app has been minimized. The music doesn't stop playing though.

https://github.com/user-attachments/assets/255359e3-8601-4c02-9bb0-8793c30e4ffe

**Comment by KieronQuinn** [comment]
This is normal and can't be fixed, the new task flag which causes this is required for Expanded Smartspace to work properly.

**Comment by mario-g98** [comment]
I have noticed that this doesn't happen with all music players. For example Auxio doesn't have this problem. What could be the reason behind this?

**Comment by KieronQuinn** [comment]
It depends on how the music app handles new launches, whether it resumes or treats it as a new start
