### ISSUE TITLE
Pagination dot getting cut on oneplus launcher

### ISSUE THREAD

**Issue by parthmawai** [KieronQuinn/Smartspacer#236]
### Description

While using the stock launcher (oneplus launcher), the first pagination dot seems to be cut. 
![Screenshot_2024-07-27-22-26-34-78_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/ab984e03-bcdd-4495-b63b-a00b1fdccb78)
I think the issue is that the launcher forces rounded corners to widgets which leads to the cornermost dot being cut
![Screenshot_2024-07-27-22-39-15-83_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/1bb42c15-699f-4a78-8590-cf3bccbe1b4f)

**Comment by KieronQuinn** [comment]
Smartspacer already opts out of rounded corners. If OnePlus ignores that opt out, there's nothing I can do.

**Comment by parthmawai** [comment]
Moving the dots a bit to the right may solve it 🤷

**Comment by KieronQuinn** [comment]
The dots are aligned with the widget and match the style of At a Glance, they're not being moved. Report the issue to OnePlus.
