### ISSUE TITLE
Widget text size slider

### ISSUE THREAD

**Issue by parthmawai** [KieronQuinn/Smartspacer#238]
### Suggestion

An option to change the font size of the widget can be helpful. Sometimes text doesn't fit the width of the screen and gets cut out. Having a slider to change the font size can add an additional layer of customization to the widget.

**Comment by KieronQuinn** [comment]
Can you send a screenshot of it being cut off please

**Comment by parthmawai** [comment]
![Screenshot_2024-08-04-21-43-35-83_b783bf344239542886fee7b48fa4b892.jpg](https://github.com/user-attachments/assets/37c562c9-0b0b-43af-bec0-04348d21ee50)

**Comment by KieronQuinn** [comment]
Shrinking the font globally isn't the fix for this. It's up to plugin developers to make sure the text fits, or to shrink it for just their Target. The title is not meant to display that much text, it would be the same with native at a glance.

**Comment by parthmawai** [comment]
Should I rather report it to plugin dev
