### ISSUE TITLE
[Bug] calendar target not showing repeating events

### ISSUE THREAD

**Issue by dot166** [KieronQuinn/Smartspacer#239]
### Description

I am using the calendar target and I was testing it and I discovered that events that are repeating are not showing on the target.

I am using the etar calendar application and syncing to google calendar if that is any help

**Comment by KieronQuinn** [comment]
Smartspacer uses the [RFC standard repetition format](https://github.com/KieronQuinn/Smartspacer/blob/main/app/src/main/java/com/kieronquinn/app/smartspacer/utils/calendar/RFC2245Duration.kt) for events, same as the system itself. It's likely the calendar app you're using isn't using it correctly. Unlike Google, I don't have the time to support every single calendar app's broken formatting, this is an issue with the sync app.

**Comment by NoName1311** [comment]
I am also affected by this issue. However, the problem is not due to etar or recurring appointments. A local calendar works perfectly. The problem is with CalDav (via DAVx5) and all-day appointments. These are not displayed.

The implemented RFC2445 standard is outdated (RFC2445 is commented in the linked source). As far as I understand, this has been replaced by RFC5545 and this has been updated by some other RFCs. I don't know the standards and their differences. This is just a hint.

Sources:
https://dl.acm.org/doi/10.17487/RFC5545
https://www.rfc-editor.org/rfc/rfc5545

**Comment by KieronQuinn** [comment]
> I am also affected by this issue. However, the problem is not due to etar or recurring appointments. A local calendar works perfectly. The problem is with CalDav (via DAVx5) and all-day appointments. These are not displayed.
> 
> The implemented RFC2445 standard is outdated (RFC2445 is commented in the linked source). As far as I understand, this has been replaced by RFC5545 and this has been updated by some other RFCs. I don't know the standards and their differences. This is just a hint.
> 
> Sources: https://dl.acm.org/doi/10.17487/RFC5545 https://www.rfc-editor.org/rfc/rfc5545

The system uses the same parser, Smartspacer's is based on that: https://cs.android.com/android/platform/superproject/+/master:frameworks/opt/calendar/src/com/android/calendarcommon2/Duration.java

I don't think it's due to an "outdated" format if it works in the system.

**Comment by NoName1311** [comment]
Just an idea what might be wrong (no debugging, no code review done):
If DAVx5 doesn't transmit the event start and end time according to RFC5545 and Smartspacer parses an event from 00:00 to 00:00, it might not show up...

https://www.rfc-editor.org/rfc/rfc5545#appendix-A

**Comment by NoName1311** [comment]
> > I am also affected by this issue. However, the problem is not due to etar or recurring appointments. A local calendar works perfectly. The problem is with CalDav (via DAVx5) and all-day appointments. These are not displayed.
> > The implemented RFC2445 standard is outdated (RFC2445 is commented in the linked source). As far as I understand, this has been replaced by RFC5545 and this has been updated by some other RFCs. I don't know the standards and their differences. This is just a hint.
> > Sources: https://dl.acm.org/doi/10.17487/RFC5545 https://www.rfc-editor.org/rfc/rfc5545
> 
> The system uses the same parser, Smartspacer's is based on that: https://cs.android.com/android/platform/superproject/+/master:frameworks/opt/calendar/src/com/android/calendarcommon2/Duration.java
> 
> I don't think it's due to an "outdated" format if it works in the system.

I'm not deep into it and don't really know much about Android development.
I just switched to Smartspace and was missing birthdays on the home screen. My server automatically generates all day events. Then I saw this issue and was trying to figure out what could be causing this behavior.
