### ISSUE TITLE
[Bug] Expanded Smartspacer: Can't add widgets from work apps

### ISSUE THREAD

**Issue by CamperSamu** [KieronQuinn/Smartspacer#246]
### Description

Android allows to use work space widgets if enabled for the work profile, while it works on apps like Lawnchair, Smartspacer won't notice the presence of a work space with exposed widgets.
The easiest way to reproduce this is by installing Shelter and enabling widgets for something like Calendar.

This feature is important because cross-profile interactions (A11+) are usually unilateral towards the workspace (so personal -> work).
In the case of an app like Calendar the only way to see a unified calendar widget is by using the workspace one for example.

**Comment by KieronQuinn** [comment]
This has been allowed in 1.9, but there's a small caveat that the app has to be installed on the main profile too. It's fine for apps like calendar, but a little annoying for anything super-work specific. Unfortunately it seems to be a system limitation - while the app can query for and add widgets from other apps, AppWidgetHost refuses to bind them unless the app also exists on the main profile. It doesn't seem to be an issue for launchers, so presumably those get special allowances.

**Comment by CamperSamu** [comment]
Thanks a lot!
