### ISSUE TITLE
[Suggestion] KernelSU support for Enhanced Mode

### ISSUE THREAD

**Issue by AK2H** [KieronQuinn/Smartspacer#247]
### Suggestion

Add support for KernelSU SuperUser profiles.
Templates can be used without the need for Shizuku or sui to be installed.

Enhanced mode fails to detect Shizuku or sui when granted by KernelSU.

**Comment by KieronQuinn** [comment]
Smartspacer heavily uses the Shizuku/Sui API. If it didn't, it would support libsu and other options already.
