### ISSUE TITLE
[Bug] Problems with music highlighting. 

### ISSUE THREAD

**Issue by GabrielHenr8** [KieronQuinn/Smartspacer#248]
### Description

When I play a song on Spotify, the first song has no photo with an incomplete album, and when I move on to the next song, it has the photo of the previous song and it continues like that. What I did so far was simply put on the music and it presented this problem.It is set to photo enabled and checkerboard when possible. And it happens both in the widget and in the expanded one.

**Comment by KieronQuinn** [comment]
The album art is sent from the music app. If it doesn't send one, Smartspacer can't display one. That's what's happening here.
