### ISSUE TITLE
[Suggestion] make option to show CLOCK not only as complication 

### ISSUE THREAD

**Issue by fbfrank** [KieronQuinn/Smartspacer#250]
### Suggestion

Clock should be a target. Currently only date is a target, and clock is only shown together with date. This means, you either have two times a date shown (vertical), or you have to find the button to move sidewards.
![Uploading Screenshot_20240919-171224_Moto App Launcher.png…]()

**Comment by KieronQuinn** [comment]
Your screenshot has not uploaded. Are you suggesting the Clock target show the time on the first or second line?

**Comment by fbfrank** [comment]
![Screenshot_20240919-171112_Moto App Launcher](https://github.com/user-attachments/assets/bc339159-b431-4d91-90cf-733d24ffe6b2)

In vertical it shows date in two lines, because date is target, and not clock.

**Comment by KieronQuinn** [comment]
Added in 1.9
