### ISSUE TITLE
[Bug] Duplicate Background Service Notification

### ISSUE THREAD

**Issue by lone-faerie** [KieronQuinn/Smartspacer#252]
### Description

After enabling Native Smartspace, there are two 'Smartspacer is running' notifications in my notification bar. It seems to be that Smartspacer restarts but doesn't dismiss the notification from before enabling Native Smartspace.

![Screenshot_20240927-145124](https://github.com/user-attachments/assets/bb590dba-a4ae-4477-b8d0-ce1b03f9da3f)

### Steps to reproduce
1. Start Smartspacer with Native Smartspace disabled
2. Enable Native Smartspace

**Comment by KieronQuinn** [comment]
This is normal and intended, you're meant to turn those off.
