### ISSUE TITLE
[Bug] Notification Targets are unable to display some notifications (unclear scheme which kind of notifications are problamatic)

### ISSUE THREAD

**Issue by rkunschke** [KieronQuinn/Smartspacer#253]
### Description

I've wanted to use a notification target to display a persistent notification. I've tried it with kde-connect and breezy weather which doesn't worked. The syncthing persistent notification worked on the other side. 
I had no problems with notification of other apps like signal, discord, whatsapp, different music/video players, etc.... Also not with the widget ones from the players.

I've really unable to find a clear scheme. For the moment it seems like the normal (not-persistent) notifications from breezy weather seem to not work either (but maybe that's doe to them being attached to the persistent notification?). Also it seems like it has nothing to do with the notifications settings (normal, silent, minimized, ... - nothing makes a different). 

Any ideas on that?

**Comment by KieronQuinn** [comment]
Post screenshots of some example notifications that don't work please.

**Comment by rkunschke** [comment]
![Screenshot_20241001-103508](https://github.com/user-attachments/assets/62054c67-b866-4986-b7f1-50b5cee64b32)
![Screenshot_20241001-103516](https://github.com/user-attachments/assets/c0cbd1da-3148-40c4-9008-975cb5ade5b6)

All the notification on the first screenshot should appear on the second. The breezy weather one is missing. The persistent from kde connect is missing while the Sent file notification shows up. That also happens when the persistent notification is the only one.
![Screenshot_20241001-104655](https://github.com/user-attachments/assets/64a8d1f7-357c-438f-b699-630106a42aba)

Here are the settings. I've enabled all notification channels on these targets.

**Comment by rkunschke** [comment]
![tmp-1727772643345](https://github.com/user-attachments/assets/fabc7ada-cac1-44e8-8ccf-7be7eb09a6db)

This notification was shown as soon I've removed the persistent notification of breezy weather (the widget one on the first screenshot)

**Comment by KieronQuinn** [comment]
They're probably using custom layouts, which are not supported because they're custom. It would require a custom plugin to support these.

**Comment by rkunschke** [comment]
I can confirm that. In breezy weather I was able to set the widget-notification to a different (native) style an it worked.

Thank you :)
