### ISSUE TITLE
[Bug] "Too many bind requests" randomly crashes Lawnchair

### ISSUE THREAD

**Issue by RWCoding58** [KieronQuinn/Smartspacer#254]
### Description

Smartspacer occasionally seems to cause Lawnchair to crash suddenly, with the error message being `java.lang.IllegalStateException: Too many bind requests(999+) for service Intent { act=com.kieronquinn.app.smartspacer.MANAGER pkg=com.kieronquinn.app.smartspacer }`. I'm not sure what causes the crash except that it obviously has something to do with the Smartspacer app, but I haven't noticed any abnormal behaviour that might have caused it.

I'm not sure how to trigger the crash since it isn't a regular occurrence, though it usually happens either when I close an app to go to the home screen or go to an app from the home screen.

I'm using Smartspacer version 1.8.1, and my phone is running Android 12 with the stock One UI ROM. 

Crash log (from Lawnchair, not Smartspacer): https://katb.in/epowefigeqo

**Comment by RWCoding58** [comment]
Any news on this?

**Comment by KieronQuinn** [comment]
Fixed in 1.1.1 of the SDK, third party apps will need to update to include that (Lawnchair has a bot that does it)
