### ISSUE TITLE
[Bug]  no information on AOD/ambient display even with all the right tonggles 

### ISSUE THREAD

**Issue by meilluer** [KieronQuinn/Smartspacer#258]
### Description

Smartspacer doesn't appear on ambient display even after all necessary device : redmi note 12 4g(tapas) with Android 14. Rising os custom rom
![Screenshot_20241023-084508_Smartspacer](https://github.com/user-attachments/assets/b26f972d-cc4b-49e2-b5a9-8cb2b76b4114)
![Screenshot_20241023-084413_Smartspacer](https://github.com/user-attachments/assets/b81b0393-b5b1-4420-a4d1-b7245d3d94c9)
![Screenshot_20241023-084508_Smartspacer](https://github.com/user-attachments/assets/4edb1fde-5f57-493f-a3ed-020df1c398bb)
![Screenshot_20241023-084357_Smartspacer](https://github.com/user-attachments/assets/053ece1f-4414-4f37-a6f5-3d11f853eb0c)
![Screenshot_20241023-084350_Smartspacer](https://github.com/user-attachments/assets/58c77ce5-da41-4836-b7e7-4993a12ae45a)
![Screenshot_20241023-083952_Smartspacer](https://github.com/user-attachments/assets/05da70c1-2da1-4a00-a6f0-5e971aca3eb9)

**Comment by KieronQuinn** [comment]
This isn't a bug, if the options don't work then your ROM is not supported.
