### ISSUE TITLE
[Bug] Target disappears and reappears at random

### ISSUE THREAD

**Issue by meilluer** [KieronQuinn/Smartspacer#259]
### Description

No requirement has been added yet Target disappears also target do not follow order set in smartspacer 
![Screenshot_20241027-111720_Lawnchair~2](https://github.com/user-attachments/assets/de8e90ee-27fa-46c2-bcc0-01b0393f71da)
![Screenshot_20241027-111717_Smartspacer](https://github.com/user-attachments/assets/9ad292c7-68db-48ba-920e-3468c7d46a88)

**Comment by KieronQuinn** [comment]
Wrong place for Keep, issues with the first party plugins go here: https://github.com/KieronQuinn/SmartspacerPlugins

As for the ordering, are you expecting a date before this Target? That's not how it works, At a Glance is not the date - add a Date Target to the top of the list if you always want the date first.
