### ISSUE TITLE
SMS Unread - honour default SMS app or allow 'launch package option'

### ISSUE THREAD

**Issue by jstride** [KieronQuinn/Smartspacer#261]
### Suggestion

As per the title - there is no way to change which app is launched by the complication. In my case I use quik (on grapheneos) and it launches the asop messaging app even though quik is the default

![Screenshot_20241028-113806](https://github.com/user-attachments/assets/9603b9d7-c613-49c5-9a5e-ffea80be2f51)

**Comment by KieronQuinn** [comment]
[It already is doing](https://github.com/KieronQuinn/Smartspacer/blob/7576d60ff43a48c9c6d7fbc960230455a63b6268/app/src/main/java/com/kieronquinn/app/smartspacer/components/smartspace/complications/SmsComplication.kt#L29). QUIK is not declaring itself with the [APP_MESSAGING category](https://developer.android.com/reference/android/content/Intent#CATEGORY_APP_MESSAGING) which the system requires to know it's a messaging app. 

Smartspacer should not need to read the messaging app role for this, I suggest you make a request to QUIK to add the category it should have.

**Comment by octoshrimpy** [comment]
TIL about categories. Feature coming to QUIK soon. :)
