### ISSUE TITLE
Android keeps saying that it's not responding.

### ISSUE THREAD

**Issue by Tophatcatt** [KieronQuinn/Smartspacer#262]
### Description

Android keeps saying that smartspacer is not responding. (I'm using expanded smarspace on nova launcher.) I'm on android 11.

**Comment by KieronQuinn** [comment]
Please post a log of that happening.

**Comment by Tophatcatt** [comment]
I'm sorry, I'm inexperienced in this. How do I provide the logs?

**Comment by KieronQuinn** [comment]
You can install an app like [LogFox](https://github.com/F0x1d/LogFox), start it recording, make it do whatever you need to do to make it display that message and then stop the recording and send the file it produces
