### ISSUE TITLE
[Bug] Smartspacer constantly crashes after first launch on Pixelstar rom

### ISSUE THREAD

**Issue by AndreyAdamenco** [KieronQuinn/Smartspacer#263]
### Description

[log.txt](https://github.com/user-attachments/files/17637143/log.txt) Cant open the app, constant crash after some time I opened it. Like it tries to run in background but cant. I have first restored the app  from "Swift backup" along with the plugins, then I first reinstalled and updated app to the latest version, then deleted all of the plugins, preforming a clean install of the app. I never had the issue with other pixel based roms as Smartpacer worked there flawlessly.

**Comment by KieronQuinn** [comment]
The crash indicates a system issue with Device Config, which is out of my hands. If a totally clean install (uninstall everything Smartspacer related and install without restoring a backup, which won't work due to the encryption) doesn't fix it, then there's nothing more I can do.
