### ISSUE TITLE
[Question] General question about dismissing devices / apps

### ISSUE THREAD

**Issue by babushanaelsa** [KieronQuinn/Smartspacer#265]
### Suggestion

Several plugins from your repo or even from third party repos have in the advanced settings section of the complecations the option to reset dismissed apps or dismissed devices.

Example:
In advanced settings of music i can delete the list of all dismissed music apps.

I wonder where I can dismiss these apps or devices in smartspacer or in the complication itself?
I use smartspacer only - without the original Google App / At a Glance widget.

Is there a section to dismiss / blacklist apps that would actually use a comlication or a target?

**Comment by KieronQuinn** [comment]
Those settings are the plugin, they're not part of Smartspacer. I'm not sure I understand your question though, what are you actually trying to do? If you don't use At a Glance, just don't add the At a Glance Target or Complication, there's nothing to blacklist.

**Comment by babushanaelsa** [comment]
I use smartspacer as my regular at a Glance widget and have configurated everything to my needs (date, calender entries, music playback and so on).

In the advanced settings of the compilation that shows the music which is currently played, there are toggles for 

> show Album cover
> show squared Album cover
> delete dismissed music apps

(maybe the wording in English is different, I use it in German)

Delete dismissed music Apps: 
as I understand these are music apps which I can blacklist so they don't show up in Smartspacer widget when they Play music - how can they be dismissed? Where is the setting for that dismissal?

**Comment by KieronQuinn** [comment]
Long press the Target and dismiss, or tap the three dots if you're using the widget.
