### ISSUE TITLE
[Bug] Settings are not applied 

### ISSUE THREAD

**Issue by QkiZMR** [KieronQuinn/Smartspacer#267]
### Description

Settings of expanded smartspace are not applied. I changed the background to blur, and nothing happened. I have hidden the add widgets button, but this does not work. I added it for Google Keep, and it displays only a summary, not widgets. 
Screenshot attached.
![Screenshot_20241124-121244](https://github.com/user-attachments/assets/110f47ab-a81f-435b-8550-dd797ccb558a)

[smartspacer_target_dump_2024-11-24T12_15_45.028771.txt](https://github.com/user-attachments/files/17893005/smartspacer_target_dump_2024-11-24T12_15_45.028771.txt)

**Comment by KieronQuinn** [comment]
Can't reproduce. Please try rebooting to see if that fixes it.

**Comment by QkiZMR** [comment]
What? So every setting change I need to reboot the phone?

**Comment by KieronQuinn** [comment]
No, I'm asking to see if rebooting your phone fixes it.

**Comment by QkiZMR** [comment]
No, still the same. I'm using Smartspacer as Google Discover replace on Nova Launcher.

**Comment by KieronQuinn** [comment]
I was unable to reproduce this in 1.9, but did change how setting listeners work to be more efficient so it may solve this. If not, there's nothing else I can do.
