### ISSUE TITLE
[Bug] I can't add some widgets to expanded smartspace

### ISSUE THREAD

**Issue by RichardLuo0** [KieronQuinn/Smartspacer#268]
### Description

Some widgets like nekogram, Google keep note can not be added. It looks like as long as the widget needs additional settings, like choosing a contact, then it can not be added.
I am on Android 15.

**Comment by KieronQuinn** [comment]
Where are you trying to add them from, the launcher overlay (swiping to the right on your home screen) or expanded smartspace launched from a shortcut?

**Comment by RichardLuo0** [comment]
swiping to the right on home screen

**Comment by KieronQuinn** [comment]
Can you try from the shortcut (long press Smartspacer and launch it from there) please

**Comment by RichardLuo0** [comment]
> Can you try from the shortcut (long press Smartspacer and launch it from there) please

this works!!

**Comment by KieronQuinn** [comment]
Yeah I think they changed something in the overlays which breaks adding widgets directly again. If I can't find a workaround it will be back to the old method of opening the full expanded Smartspace to add a widget.

**Comment by slash-drumbler** [comment]
I am also having this issue, tried using both methods but I cannot add any widgets that require further options. In my case, trying to add Home Assistant widgets where I would need to select an entity etc.

Any thoughts?
Cheers
Running GrapheneOS (Android 15)

**Comment by KieronQuinn** [comment]
Should be fixed in 1.9
