### ISSUE TITLE
[Bug] Gmail complication does not work with non-gmail email

### ISSUE THREAD

**Issue by RichardLuo0** [KieronQuinn/Smartspacer#269]
### Description

I added outlook to Gmail app, but it doesn't show up in smartspacer, only gmail.

**Comment by KieronQuinn** [comment]
Unfortunately the Gmail complication is reliant on [GmailContract](https://developers.google.com/gmail/android/com/google/android/gm/contentprovider/GmailContract), which seems to only support Gmail. You may wish to use the K9 plugin instead.
