### ISSUE TITLE
[Bug] Smartspacer feedback loop crashes and restarts Pixel 8 Pro

### ISSUE THREAD

**Issue by devnblack** [KieronQuinn/Smartspacer#271]
### Description

After the December 2024 update Smartspacer gives the encounters feedback loop error and upon attempting to reconnect and getting the system UI keeps crashing notification the phone freezes and then reboots.

**Comment by KieronQuinn** [comment]
Please post a log, SystemUI crashes are not reported to Crashlytics.

**Comment by devnblack** [comment]
I did a clean install and that's working so I'll close for now
