### ISSUE TITLE
[Suggestion] Fix for Material You Breaking Smartspacer

### ISSUE THREAD

**Issue by eliasacab** [KieronQuinn/Smartspacer#276]
### Suggestion

I was able to fix issue [#273](https://github.com/KieronQuinn/Smartspacer/issues/273) (and [#87](https://github.com/KieronQuinn/Smartspacer/issues/87)) with Tasker.

I created a profile that reacts to the setting "theme_customization_overlay_packages" being changed (no value), which triggers a task that creates a notification quietly and dismisses it right after.  In Smartspacer, I have a target for that Notification. As a result, whenever I change themes (or wallpapers), Smartspacer continues working.

My suggestion is, could something like this be added to Smartspacer natively? Something like reacting to this setting being changed and sending a target update which would make Smartspacer functional again after the theme change. Thanks for considering!

**Comment by KieronQuinn** [comment]
Good spot, thanks - I didn't know a setting existed that apps could query. 1.9 now adds that to the list of stuff it listens to.
