### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Keatondickens** [KieronQuinn/Smartspacer#277]
### Description

So when I play any sort of media (e.g YouTube, Spotify) the Media player that is on the lock screen is not showing up at all it's fine in the notification bar but not on the lock screen, but when turn off native Smartspace it comes back.

**Comment by Keatondickens** [comment]
![Screenshot_20241218-005846](https://github.com/user-attachments/assets/53ad2dfb-b4b4-469a-b7b2-259a2d448e10)
The pixel one on the lock screen.

**Comment by Keatondickens** [comment]
![Screenshot_20241218-010513](https://github.com/user-attachments/assets/7dc2e66c-3f4b-4288-a502-d8530552dea7)
This is with native smartspace active.

**Comment by KieronQuinn** [comment]
Set the music target to not appear on the lock screen, this isn't a bug.
