### ISSUE TITLE
[Bug] 1.8.2 does not fix Android 15 crashes. Ca

### ISSUE THREAD

**Issue by Anihilitus** [KieronQuinn/Smartspacer#278]
Can't even open the app now

**Comment by Anihilitus** [comment]
![Screenshot_2024-12-18-12-34-17-513_com miui bugreport](https://github.com/user-attachments/assets/92e5baa7-907f-4844-b055-a0234b2c1522)

**Comment by KieronQuinn** [comment]
#263 not related to Android 15
