### ISSUE TITLE
Local Plugin Complication Testing

### ISSUE THREAD

**Issue by owenlejeune** [KieronQuinn/Smartspacer#28]
### Issue

Is there currently a way to test that my complication is working without uploading it to the plugin repository?

Also, when building a complication that displays information from a companion app, is it recommended that we build the complication into the application or as a separate APK?

**Comment by KieronQuinn** [comment]
Plugins are regular APKs, so just install it as normal and it will appear in the app. As for companion apps, it's up to you: You can include it as part of your regular app (and then link it in the repository submission as normal), or make a separate plugin app and link that from the repository. Both work.

**Comment by owenlejeune** [comment]
Duh! I was looking for an option to install the complication and didn't even think that it was already installed. Thanks for the info!
