### ISSUE TITLE
Shows twice on lock screen and color on aod

### ISSUE THREAD

**Issue by niruvibes** [KieronQuinn/Smartspacer#31]
### Issue

When on the lock screen the date shows up two times, one from the normal lock screen and one from the at a glance (I think)
Ok the always on display the headset icon is also coloured, it is possible to grey scale it 
![Screenshot_20231104-160831](https://github.com/KieronQuinn/Smartspacer/assets/67180137/380ed2b2-38e4-4ab1-a2e5-18717c58cb58)

**Comment by KieronQuinn** [comment]
The double date isn't a bug, you need to add a Target like the greeting or blank one.

The icon colour is a plugin, here is the wrong place to report plugin issues. 

https://github.com/KieronQuinn/SmartspacerPlugins/issues.
