### ISSUE TITLE
Youtube subscriber count plugin is not refreshing 

### ISSUE THREAD

**Issue by Mark4256** [KieronQuinn/Smartspacer#32]
### Issue

Subscriber count is not refreshing as expected. In the plugin settings page error shows as "the last refresh failed. Check your connection and try again". When I first installed smartspacer couple of days ago, it worked without an issue. But now it's not refreshing. Kindly look into this issue. Thank you.

**Comment by KieronQuinn** [comment]
This is the wrong place to report plugin issues, please read the message in the issue creation form next time. You want https://github.com/KieronQuinn/SmartspacerPlugins

You should also provide screenshots there.
