### ISSUE TITLE
[Bug]  Amazon Plugin

### ISSUE THREAD

**Issue by ElderHallow** [KieronQuinn/Smartspacer#33]
### Description

Hi! I have the Amazon Plugin installed.

On my home screen it asks me to sign in. But in the app itself it's says I am signed in. Am I doing something wrong or is this a bug. Please see screenshots:
![Screenshot_20231105-093937](https://github.com/KieronQuinn/Smartspacer/assets/83273463/9bc261ea-8b84-44a0-957a-7f7b18f4674c)
![Screenshot_20231105-094417](https://github.com/KieronQuinn/Smartspacer/assets/83273463/f87f3fa1-f0a5-4c95-9b52-a5708240a164)
![Screenshot_20231105-094423](https://github.com/KieronQuinn/Smartspacer/assets/83273463/8e809070-6b63-46aa-a96c-95d2d8d130fe)
![Screenshot_20231105-094556](https://github.com/KieronQuinn/Smartspacer/assets/83273463/fccc3741-5a67-4d0d-a2b0-abd4644ad069)

Pixel 5 Android 14. Thanks for your help 😃

**Comment by KieronQuinn** [comment]
This is the wrong place for plugin issues, they go on https://github.com/KieronQuinn/SmartspacerPlugins/issues. Please read the message that's at the top when you make an issue next time.
