### ISSUE TITLE
[Bug] Device Unsupported

### ISSUE THREAD

**Issue by heckarman** [KieronQuinn/Smartspacer#34]
### Description

Device: Bluejay
Android: GrapheneOS A14
Launcher: [Lawnchair Debug](https://github.com/LawnchairLauncher/lawnchair/suites/17900127749/artifacts/1028067062)
![Screenshot_20231105-234739](https://github.com/KieronQuinn/Smartspacer/assets/147484873/831e4fd5-c318-490c-b1b7-098b5eb41c75)
[backup.smartspacer.zip](https://github.com/KieronQuinn/Smartspacer/files/13260466/backup.smartspacer.zip)

**Comment by KieronQuinn** [comment]
This isn't a bug, your firmware doesn't support it.

**Comment by heckarman** [comment]
So the app will never support GrapheneOS?

**Comment by KieronQuinn** [comment]
The app supports GrapheneOS perfectly fine. The At a Glance Target & Complications require Android System Intelligence support, which your firmware does not have. Again, this is not a bug.

**Comment by heckarman** [comment]
Cool, got it. If ASI is supported by GOS, then the app will work.  
I might have to make my Magisk module work now to get this app working.
