### ISSUE TITLE
[Suggestion] Adapt expanded smartspace for large screens with multiple columns

### ISSUE THREAD

**Issue by Jnss98b** [KieronQuinn/Smartspacer#42]
### Suggestion

The expanded smartspace should display info more densely on large-screen devices by using multiple columns. I'd also like to request this to be implemented adaptively since book-style foldable devices have 2 different screen sizes and a single settable value would work well for one but not the other.

Currently, everything is displayed in one column no matter how large the display is:
![image](https://github.com/KieronQuinn/Smartspacer/assets/24306400/c86d4a2c-c8ab-498e-8f2b-93468d755586)

**Comment by KieronQuinn** [comment]
Added in 1.3
