### ISSUE TITLE
[Bug] Google weather forecast target animation to AOD is glitchy

### ISSUE THREAD

**Issue by Giggigx** [KieronQuinn/Smartspacer#43]
### Description

I don't know if this is down to google's smartspace implementation having this buggy animation, so this bug report may be totally useless. 

When the Google weather forecast target is used on the lockscreen/AOD, the animation that happens when turning off the screen gets real glitchy when the text of the weather condition is longer than the forecast image since it can't be totally hidden behind said image anymore. If the animation is done by smartspacer I may suggest to add a fade out transition to the weather image or something that gets it out of the way so that it doesn't obstruct the text. 
I have attached a video so that you can see what I'm talking about.

https://github.com/KieronQuinn/Smartspacer/assets/38881699/3ec89667-b7da-4029-851f-64e3da6df65c

**Comment by KieronQuinn** [comment]
This isn't something Smartspacer controls unfortunately, so I can't fix it.
