### ISSUE TITLE
Lock screen is failing compatibility checks in Android 14[Bug] 

### ISSUE THREAD

**Issue by HrithikMJ** [KieronQuinn/Smartspacer#44]
### Description

Hi,
The lock screen is failing all the compatibility checks in PixelExperience android 14. 

![image](https://github.com/KieronQuinn/Smartspacer/assets/31767239/ff8f0f3a-4f11-4bc4-90d1-9fc6188eaa09)

**Comment by KieronQuinn** [comment]
This isn't a bug, your firmware isn't compatible. The compatibly check is working fine.

**Comment by HrithikMJ** [comment]
> This isn't a bug, your firmware isn't compatible. The compatibly check is working fine. 

Is there anything I can do to fix it?

**Comment by KieronQuinn** [comment]
Flash a different ROM with support is the only way. Pixel Experience is supposed to have support but clearly it does not on your device.

**Comment by HrithikMJ** [comment]
> Flash a different ROM with support is the only way. Pixel Experience is supposed to have support but clearly it does not on your device. 

Alright man , thanks for your time.
