### ISSUE TITLE
Music target not working at Apple Music

### ISSUE THREAD

**Issue by XiaoMouz** [KieronQuinn/Smartspacer#47]
### Description

When I using Apple Music play sound, the start play is good working, when I change music player（us another player like Netease Music, Spotify) and when I switch back, the target look like didn't know Apple Music playing music, I tried Clear dismissed Apps, it doesn't work.

And, when I switch sound in Apple Music in widget the target still lost playing status and didn't recovery.

**Comment by KieronQuinn** [comment]
The Music Target relies on apps sending their state to the system. If the app isn't sending its state correctly, it may not be picked up, and there's nothing I can do about that. It's not my bug to fix.
