### ISSUE TITLE
[Other] Release on F-Droid.

### ISSUE THREAD

**Issue by ukrbugreporter** [KieronQuinn/Smartspacer#48]
### Issue

F-Droid is a repository (and app store) of free and open-source Android apps. They take the source code directly from the developer and build it themselves to ensure that it is reproducible and does not require proprietary dependencies. To include your app in the F-droid repo, first read their [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) and then [request inclusion at their GitLab](https://gitlab.com/fdroid/rfp/-/issues).

**Comment by KieronQuinn** [comment]
It immediately fails the first two requirements for building. I don't publish to F-droid for this reason. If anyone wants to fork it or publish to a less restrictive repository, that's up to them, but I don't.
