### ISSUE TITLE
[Bug] HealthConnect plugin can not install

### ISSUE THREAD

**Issue by Mystery00** [KieronQuinn/Smartspacer#5]
### Description

Summary:
I encountered a problem while attempting to install the HealthConnect plugin on my device. When I click the "Install" button in the plugin repository of the application, the installation dialog appears as expected. However, upon clicking the "Install" button within the dialog, the dialog disappears without any indication or response from the system, and the plugin fails to install successfully.

Steps to Reproduce:

Open the application.
Navigate to the plugin repository.
Locate the HealthConnect plugin.
Click on the "Install" button for the HealthConnect plugin.
Observe the installation dialog that appears.
Click the "Install" button within the dialog.
Expected Result:
The installation dialog should remain visible, and the system should initiate the installation process for the HealthConnect plugin. Eventually, the plugin should be successfully installed on the device.

Actual Result:
After clicking the "Install" button within the installation dialog, the dialog disappears without any response from the system. The HealthConnect plugin fails to install.

Additional Information:
I attempted to manually install the HealthConnect plugin by downloading the APK package from https://github.com/KieronQuinn/SmartspacerPlugins, but encountered the same issue.

Device Details:

Device: Pixel 6 Pro
Operating System: Android 14
ROM: Stock Rom
Build Number: U1B2.230922.010

**Comment by Mystery00** [comment]
https://github.com/KieronQuinn/Smartspacer/assets/19162205/a927e74a-fe4a-41b7-95f2-f41b36f28361

**Comment by KieronQuinn** [comment]
The install interaction here is simply invoking the package installer: https://github.com/KieronQuinn/Smartspacer/blob/9e48bcc23b598ffc487b6a8a1f8064c7d1a1c07b/app/src/main/java/com/kieronquinn/app/smartspacer/ui/screens/repository/details/PluginDetailsViewModel.kt#L237

Given you're seeing the same thing when installing it manually, I suspect something on your device is blocking the install. I've just checked, and it can install fine on my devices. 

I'm going to close this as out of my hands, all I can suggest is perhaps use a session based installer like SAI and see if that gives any more of a reason.
