### ISSUE TITLE
[Suggestion] Allow more than two complications on a single page of the widget

### ISSUE THREAD

**Issue by h0tk3y** [KieronQuinn/Smartspacer#50]
### Suggestion

Given that the Smartspacer widget may get a lot of horizontal space, it would make sense to allow more than just two complications to appear inline, so that there is no (or less) need to switch pages in order to see them all. 

The two screenshots demonstrate the idea: even with another widget to the right of Smartspacer, there is plenty of horizontal space to fit the three complications that I would like to use. 

![image](https://github.com/KieronQuinn/Smartspacer/assets/1888526/a2fddd9e-2ee7-46ce-b676-d2068cb8be6c)
![image](https://github.com/KieronQuinn/Smartspacer/assets/1888526/f7821c96-4da4-4e89-9b00-fb971a6be43a)

**Comment by KieronQuinn** [comment]
Not possible, and please search next time as this has already been rejected for the exact same reason.

#30.

**Comment by MrNeocore** [comment]
@KieronQuinn Is this still an impossible feature request ? It looks minor but is a deal breaker to me

**Comment by KieronQuinn** [comment]
Yes. The templates are not dictated by me and that will never change now.

**Comment by MrNeocore** [comment]
Okay, thanks for the update
