### ISSUE TITLE
[Suggestion]  2 suggestions extended spacees & timer Complications

### ISSUE THREAD

**Issue by nick123456789025** [KieronQuinn/Smartspacer#51]
### Suggestion

Add an option to automatically close extended spacees when the power button is pressed or the phone/device goes to sleep, and add a Complication to show the status of the timer (from the notification or something)

**Comment by KieronQuinn** [comment]
You can already close expanded when the device is locked, there's an option for it in the settings. The timer suggestion already works via At a Glance too, but I see you've made a plugin request for a Complication for devices without At a Glance.

**Comment by nick123456789025** [comment]
I'm not talking about closing expanded smartspaces automatically when the device is initially locked I'm trying to get it to close when you hit the power button after the device has already been locked on the Pixel 6 pro when you open the expanded spaces from one of the targets, it does not close when pressing the power button, I already looked through settings and I already have that option turned on. I've attached a video to show how it isn't closing (device is already locked).

(When the always-on display shows up that is when I've pressed the power button.)

https://github.com/KieronQuinn/Smartspacer/assets/55955972/8f42e49c-b4db-46f8-b87f-d0994ac139e9

**Comment by nick123456789025** [comment]
And for the timer I'm talking about getting the timer from the clock app and when I mentioned notification  I was going off of the script that I was given, when making the issue it said to add a way of accessing the data I didn't realize it appeared this way sorry for the confusion. I meant to get the data from the notification that is in the notification bar (from the clock app).
