### ISSUE TITLE
Crashing shizuku after qpr2 update[Bug] 

### ISSUE THREAD

**Issue by mcdaveey** [KieronQuinn/Smartspacer#52]
### Description

After updating to qpr2 update on my pixel fold, smart spacer forcecloses and then keeps asking for permission with shizuku. Shizuku then will say it's not running when you try to enable smart spacer.

**Comment by KieronQuinn** [comment]
I think this is a Shizuku issue not a Smartspacer issue, so we need to wait for Shizuku to be updated. This error shows in the logs:

```
11-15 22:11:13.392  9278 10659 E AndroidRuntime: java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
11-15 22:11:13.392  9278 10659 E AndroidRuntime:        at rikka.shizuku.l70.b(SourceFile:18)
11-15 22:11:13.392  9278 10659 E AndroidRuntime:        at rikka.shizuku.server.ShizukuService.y(SourceFile:206)
11-15 22:11:13.392  9278 10659 E AndroidRuntime:        at rikka.shizuku.qt$a.onTransact(SourceFile:20)
11-15 22:11:13.392  9278 10659 E AndroidRuntime:        at rikka.shizuku.server.c.onTransact(SourceFile:64)
11-15 22:11:13.392  9278 10659 E AndroidRuntime:        at rikka.shizuku.server.ShizukuService.onTransact(SourceFile:26)
11-15 22:11:13.392  9278 10659 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1362)
11-15 22:11:13.392  9278 10659 E AndroidRuntime:        at android.os.Binder.execTransact(Binder.java:1301)
```

After granting the permission manually in the app info for Smartspacer (Permissions > Additional permissions > Shizuku > Allow), I can start it fine. Running the command manually also works fine, so it's definitely not been patched.

**Comment by mcdaveey** [comment]
Just making you aware more so, I did what you did, shizuku has stopped complaining but I still have smartspacer force closing after a few seconds

**Comment by KieronQuinn** [comment]
Smartspacer is detecting an abnormal state of Shizuku and crashing it seems, but the bug definitely lies in Shizuku. There is a workaround, but it's not pretty and has to be done every time Shizuku crashes. See this video:

https://github.com/KieronQuinn/Smartspacer/assets/3430869/795491ac-5caa-4871-aa15-badb73025fed

I'm going to keep this open so the issues don't get bombarded with the same thing over and over, but there's nothing for me to actually do to fix it.

**Comment by mcdaveey** [comment]
I followed the work around, it works! I think I've found what's causing my particular issue.. it's the Google weather forecast, either as a target or a complication and it crashes smartspacer and then when we you try to reopen it, it just force closes

**Comment by KieronQuinn** [comment]
You're right, there's a widget change that's caused this. Funnily enough, I've been seeing this crash for a few days on Crashlytics, despite the beta only launching tonight. Someone's been using the app with a pre-beta build 👀

**Comment by KieronQuinn** [comment]
Shizuku report is here: https://github.com/RikkaApps/Shizuku/issues/373

**Comment by KieronQuinn** [comment]
For those of you on Android 14 QPR2, I have attached a (zipped) build of Shizuku which fixes its permission related crash. This should hopefully be merged into the main Shizuku builds soon, but it has to go through two layers of pull request + a library build so this may take some time.

⚠️ You will need to uninstall your existing Shizuku app to use this, and when the fix makes it into the main builds you will need to uninstall it again to switch back to the Google Play builds. This will r
eset your granted apps, and you may need to force stop apps (including Smartspacer) to get it to switch Shizuku version after installing ⚠️

[shizuku-v13.5.2.r1032.cc5c022-release.zip](https://github.com/KieronQuinn/Smartspacer/files/13398040/shizuku-v13.5.2.r1032.cc5c022-release.zip)

**Comment by KieronQuinn** [comment]
Shizuku now has a release that fixes this.
