### ISSUE TITLE
[Suggestion] Calendar Target Settings: Hide event after start

### ISSUE THREAD

**Issue by jrlebbs** [KieronQuinn/Smartspacer#53]
### Suggestion

Currently, the Calendar Target has a setting for "Show event before" and allows you to set a time. I'd like to propose a "hide after" option, which would let you hide an event after the start time or default to the end time. The native At A Glance shows at 30 minutes before and hides either at start or about 5 minutes after, not quite sure which one.

**Comment by KieronQuinn** [comment]
Added in 1.3
