### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by gchatou21r** [KieronQuinn/Smartspacer#6]
### Description

I use smartspacer on pixel 7 pro with lineage rom and every time I go on home screen the widget flashes.

**Comment by KieronQuinn** [comment]
Please provide a the configuration of your targets and complications, or a backup

**Comment by gchatou21r** [comment]
![Screenshot_20231026-003437_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/123263521/18093638-4ab7-4541-9caf-04317f81086c)
![Screenshot_20231026-003447_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/123263521/e4b7ad60-834f-4a27-8035-29cb3fa2c9ae)

**Comment by KieronQuinn** [comment]
I can't reproduce it with that setup. What launcher are you using?

**Comment by gchatou21r** [comment]
Los launcher, Trebuchet.

**Comment by KieronQuinn** [comment]
I wasn't able to reproduce this even on Trebuchet but added an option to disable animations instead which will workaround it.

**Comment by gchatou21r** [comment]
> I wasn't able to reproduce this even on Trebuchet but added an option to disable animations instead which will workaround it.

I just tested it with animations off and it's fixed.
