### ISSUE TITLE
[Suggestion]  Resizing

### ISSUE THREAD

**Issue by nichrsgit** [KieronQuinn/Smartspacer#63]
### Suggestion

Please enable, if possible, the option to resize the widget horizontally beyond the default 4x1. I know it's possible to simply leave the empty space next to the widget, but there are several strong reasons why resizing is a better option and I list them below:

* New installed apps automatically occupy the empty space left on the screen (for personal preference, I disable the app drawer and all apps are automatically added to the home screen);

* It is much more aesthetically pleasing for the three dots (options) and navigation arrows to be on the far right of the screen, not in the middle;

* The most important reason for me: I use Samsung's stacked widgets option on my main screen, which allows me to use several widgets in a carousel in the same space, as long as they are the same size. Since Smartspacer cannot be resized, I cannot add it to my stack.

To conclude, I am available to help with the translation into Portuguese, if necessary.

Thank you for your attention.

![Screenshot_20231201_080141_One UI Home](https://github.com/KieronQuinn/Smartspacer/assets/96312964/f4ac1fa8-8cec-4c23-85b7-3d7cc6955e3f)

**Comment by KieronQuinn** [comment]
This was already added in the latest update (max width is 99999). If it's not working for you, it's a problem with your launcher not Smartspacer.
