### ISSUE TITLE
Widget bug in One UI 6.0

### ISSUE THREAD

**Issue by Mark4256** [KieronQuinn/Smartspacer#64]
### Description

After I updated to the One UI 6 (Android 14) the widget scrolling appears to be not working correctly. As you can see in the screen recording, when I tap the scrolling dots whole home screen page swiped one way. I tried both arrow and non-arrow widget styles but same thing happens. I really love this app and please check on this if you can.

https://github.com/KieronQuinn/Smartspacer/assets/149863997/8831290d-2a7e-488e-b1f7-747361014251

**Comment by KieronQuinn** [comment]
This is a OneUI bug unfortunately, the widget has no control over the home screen interactions. You'll need to report this to Samsung.

**Comment by Mark4256** [comment]
I just found something that might cause this bug. I turned off the 'Animate changes' setting in the widget settings and then the auto glide effect of the screen was gone.

![Screenshot_20231203_104551_Smartspacer](https://github.com/KieronQuinn/Smartspacer/assets/149863997/413e86ed-29a5-4ead-afb9-70057180f2d8)

**Comment by Mark4256** [comment]
> This is a OneUI bug unfortunately, the widget has no control over the home screen interactions. You'll need to report this to Samsung.

Thank you for your attention sir.

**Comment by KieronQuinn** [comment]
> I just found something that might cause this bug. I turned off the 'Animate changes' setting in the widget settings and then the auto glide effect of the screen was gone.
> 
> ![Screenshot_20231203_104551_Smartspacer](https://private-user-images.githubusercontent.com/149863997/287498645-413e86ed-29a5-4ead-afb9-70057180f2d8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1ODE1MzMsIm5iZiI6MTcwMTU4MTIzMywicGF0aCI6Ii8xNDk4NjM5OTcvMjg3NDk4NjQ1LTQxM2U4NmVkLTI5YTUtNGVhZC1hZmI5LTcwMDU3MTgwZjJkOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwNTI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWVjZDFjNmYzOTljOWZhM2MwZGRkMmUxY2FkNjY2NjUxNmZjYzIxOWRkNjJkMmU2MjU1NzIxOTQ3NzM0NTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u9kdb3x19HjSxR4Qe6ozF2b5BL_VLxQBW9ggwBQUKks)

Just leave it off then. It's clear Samsung have broken something animation related, it's not for me to fix.
