### ISSUE TITLE
[Bug] Next Alarm complication 

### ISSUE THREAD

**Issue by KhaiCo** [KieronQuinn/Smartspacer#68]
### Description

So for the next Alarm complication, it is supposed to show an alarm thats set within the next 12 hour and **presumably** not show anything without such alarms. So my problem is 
1. The complication not hiding/disappearing while there is no alarm

https://github.com/KieronQuinn/Smartspacer/assets/130490107/ccdca156-4502-4661-831c-1a68b774df76

^As you can see in the video above, when there is no alarm enabled the complication just shows 00:00 which I **presume** is not supposed to be the case.

2. An alarm that is within 12 hours but the next day not showing up

https://github.com/KieronQuinn/Smartspacer/assets/130490107/50735eb8-ec2b-4297-9fe0-01eed8ebd0f6

^as seen in the video above, when there is an alarm within 12 hours but in a different day the clock does not show it but instead shows 00:00 and also seen in the video, after testing it with a different alarm in the same day it works normally which is **probably** not how it's supposed to work considering the description of the complication specifically only mentions "next alarm in 12 hours" and not "next alarm in 12 hours in the same day"

Don't think it'll help but here's my dump:
[smartspacer_target_dump_2023-12-03T22_45_46.754056.txt](https://github.com/KieronQuinn/Smartspacer/files/13539480/smartspacer_target_dump_2023-12-03T22_45_46.754056.txt)

**Comment by KhaiCo** [comment]
> Are you using Tasker at all?

Nope, never used it

**Comment by KhaiCo** [comment]
> Usually this is caused by another app abusing the alarm feature (Tasker does this by default). The alarm time comes from the system, so if the Complication says midnight then an app has an alarm at that time. If you tap the Complication, what app does it open?

I've tested it and the complication does nothing, but if there is a valid alarm (as in within 12 hours of the same day) it will open the clock app.

As demonstrated here (watch white spot indicating tap):

https://github.com/KieronQuinn/Smartspacer/assets/130490107/12a16e60-54f6-4fea-b5d7-cdf0f36789b5

**Comment by KieronQuinn** [comment]
Hmm maybe the Complication should ignore an alarm without anything to open then, though the Android documentation doesn't _require_ this to be set so it may cause some false positives for apps who are genuinely using alarms.

**Comment by KhaiCo** [comment]
> Hmm maybe the Complication should ignore an alarm without anything to open then, though the Android documentation doesn't _require_ this to be set so it may cause some false positives for apps who are genuinely using alarms.  

I see, so is the other issue of not showing the next alarm within 12 hours if it's the next day related or it's just the way it's supposed to work?
(Sorry for my late reply, I fell asleep after my last comment)

**Comment by KieronQuinn** [comment]
> > > > Hmm maybe the Complication should ignore an alarm without anything to open then, though the Android documentation doesn't _require_ this to be set so it may cause some false positives for apps who are genuinely using alarms.
> > > 
> > > 
> > > I see, so is the other issue of not showing the next alarm within 12 hours if it's the next day related or it's just the way it's supposed to work? (Sorry for my late reply, I fell asleep after my last comment)
> > 
> > 
> > It shows whatever the system reports. If there's an alarm that isn't showing, there's nothing I can do.
> 
> Ah I see, is this issue present on your side? Or is it just a device specific issue? And if it is device specific, is there anything I can do on my side to possibly fix this?

It seems to be device specific.

**Comment by KhaiCo** [comment]
> > > > > Hmm maybe the Complication should ignore an alarm without anything to open then, though the Android documentation doesn't _require_ this to be set so it may cause some false positives for apps who are genuinely using alarms.
> > > > 
> > > > 
> > > > I see, so is the other issue of not showing the next alarm within 12 hours if it's the next day related or it's just the way it's supposed to work? (Sorry for my late reply, I fell asleep after my last comment)
> > > 
> > > 
> > > It shows whatever the system reports. If there's an alarm that isn't showing, there's nothing I can do.
> > 
> > Ah I see, is this issue present on your side? Or is it just a device specific issue? And if it is device specific, is there anything I can do on my side to possibly fix this?
> 
> It seems to be device specific. 

Hey, after a few reboots it suddenly works but I don't know why it shows the alarm an hour too early? Any idea why?

![Screenshot_2023-12-04-19-05-21-728_app.lawnchair.debug.png](https://github.com/KieronQuinn/Smartspacer/assets/130490107/32b2dfe4-2d5d-4205-b12b-bb5e8201df82)

![Screenshot_2023-12-04-19-05-35-116_com.android.deskclock.png](https://github.com/KieronQuinn/Smartspacer/assets/130490107/411a2695-c8f4-4284-9e4e-6d6a2372752f)

**Comment by KieronQuinn** [comment]
> > > > > > Hmm maybe the Complication should ignore an alarm without anything to open then, though the Android documentation doesn't _require_ this to be set so it may cause some false positives for apps who are genuinely using alarms.
> > > > > 
> > > > > 
> > > > > I see, so is the other issue of not showing the next alarm within 12 hours if it's the next day related or it's just the way it's supposed to work? (Sorry for my late reply, I fell asleep after my last comment)
> > > > 
> > > > 
> > > > It shows whatever the system reports. If there's an alarm that isn't showing, there's nothing I can do.
> > > 
> > > 
> > > Ah I see, is this issue present on your side? Or is it just a device specific issue? And if it is device specific, is there anything I can do on my side to possibly fix this?
> > 
> > 
> > It seems to be device specific.
> 
> Hey, after a few reboots it suddenly works but I don't know why it shows the alarm an hour too early? Any idea why?
> 
> ![Screenshot_2023-12-04-19-05-21-728_app.lawnchair.debug.png](https://private-user-images.githubusercontent.com/130490107/287691803-32b2dfe4-2d5d-4205-b12b-bb5e8201df82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDM2MTksIm5iZiI6MTcwMTcwMzMxOSwicGF0aCI6Ii8xMzA0OTAxMDcvMjg3NjkxODAzLTMyYjJkZmU0LTJkNWQtNDIwNS1iMTJiLWJiNWU4MjAxZGY4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNTIxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjA1NmZiNzEwZTJkNmM1Yjk0YmI4NDNhNTRmMjk5NzY5ZWI2YmIwMGQ4MWMxNzQxM2MxMDliNzBlOTQ1MjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IOUUWd_8YSxeSrjECvh65_wWGBdoUcBCT4EXWARnh5E)
> 
> ![Screenshot_2023-12-04-19-05-35-116_com.android.deskclock.png](https://private-user-images.githubusercontent.com/130490107/287691802-411a2695-c8f4-4284-9e4e-6d6a2372752f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MDM2MTksIm5iZiI6MTcwMTcwMzMxOSwicGF0aCI6Ii8xMzA0OTAxMDcvMjg3NjkxODAyLTQxMWEyNjk1LWM4ZjQtNDI4NC05ZTRlLTZkNmEyMzcyNzUyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNFQxNTIxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjJiOGM1YzRiYjgzNTM3ZDMwN2ExYzhlMmQ1ZmI0YzlkOWY5ZjU0ZDA1MTUyMmI3NDg4ZDA3ZWJiNTQ4YTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PlmAxa6RLlanCVKQgpWsFARootBibXUiBwgZKojWTbU)

Again, the time is provided by the system. If it's wrong, there is nothing I can do. 

It's pretty clear this API is extremely unreliable on your device and the OEM has pretty much broken it entirely. There is unfortunately no alternative, so I cannot fix it.

**Comment by KieronQuinn** [comment]
1.3.2 no longer shows alarms without a launch intent, which is as far as I'm willing to go to fix OEM shit.
