### ISSUE TITLE
Always displays "Background Location Required, Tap to Grant"

### ISSUE THREAD

**Issue by dot-Justin** [KieronQuinn/Smartspacer#69]
### Description

Basically no matter what I do, it always displays "Background Location Required, Tap to Grant", and tapping does nothing.
![Screenshot_20231203-123158](https://github.com/KieronQuinn/Smartspacer/assets/151479459/525b3ce1-59e6-4b05-a919-b761f8248daf)

**Comment by KieronQuinn** [comment]
This is a plugin issue so it's in the wrong place, but the solution has been said a load of times: Add the Google Maps Traffic widget to your home screen and follow the steps.
