### ISSUE TITLE
[Other/Doc] Mention `sdk-core` as a dependency

### ISSUE THREAD

**Issue by gargakshit** [KieronQuinn/Smartspacer#7]
### Issue

Currently, `sdk-plugin` does not depend on `sdk-core`. Class `SmartspaceTarget` is a part of `sdk-core` which needs to be explicitly installed.

Either make `sdk-plugin` depend on `sdk-core`, or mention `sdk-core` in the documentation.

**Comment by KieronQuinn** [comment]
This isn't actually intended, the transient dependency is supposed to be available when using sdk-client and sdk-plugin. I think I may need to mark them as `api` not `implementation`, which will require a .1 SDK release

**Comment by gargakshit** [comment]
> This isn't actually intended, the transient dependency is supposed to be available when using sdk-client and sdk-plugin. I think I may need to mark them as `api` not `implementation`, which will require a .1 SDK release

Makes sense. From my testing, the `SmartspaceTarget` model was available inside the library but not the app module.

**Comment by KieronQuinn** [comment]
This is now sorted in .1 for core & plugin, and .3 for client
