### ISSUE TITLE
[Bug] Calendar target showing one complication

### ISSUE THREAD

**Issue by sammukhgupta** [KieronQuinn/Smartspacer#71]
### Description

When the calendar target shows an event with duration, it also additionally shows one complication. Can the calendar show only event without any other data?

**Comment by KieronQuinn** [comment]
No, this is out of scope for the regular Calendar Target. A plugin could do this, but that level of customisation is not something I'll be adding to the built in one.

This is also not a bug, it's a feature request. Please don't label requests as bugs.
