### ISSUE TITLE
[Bug] expanded smartspace set to always not working

### ISSUE THREAD

**Issue by sammukhgupta** [KieronQuinn/Smartspacer#72]
### Description

Expanded smartspace is set to always under homescreen. However, the individual item clicks take to actual target instead of openning the Expanded view first, as suggested in the app.

**Comment by KieronQuinn** [comment]
Can you post a screen recording please

**Comment by KieronQuinn** [comment]
No screen recording provided, closing.

**Comment by KieronQuinn** [comment]
> @KieronQuinn same issue. please reopen the issue, here's a screen record https://youtu.be/y_kK6c5YjkQ

The Date target shown here cannot open expanded smartspace, this isn't a bug it's how it works.
