### ISSUE TITLE
[Suggestion] Optimization of memory footprint

### ISSUE THREAD

**Issue by ONE223** [KieronQuinn/Smartspacer#74]
### Suggestion

Android version：14 (UP1A.231105.001)
Device：Pixel 5 

Hello developers
       I've noticed that after using the hook plugin on my device, the memory footprint of the plugin for the device fluctuates a lot.It starts out at around 120mb, gets bigger and bigger as I spend more time in the foreground (around 350mb), then at some point it suddenly decreases, and then the cycle goes on from there.It doesn't stay up and down in a range like other apps, not sure if it's a feature of the plugin or a compatibility issue?
No additional mods added, no lsposed enabled, just using shizuku.
Thank you

**Comment by KieronQuinn** [comment]
It fluctuates due to what it's doing at the time, which plugins (including the included ones). I've already tried to optimise it as much as possible, the app is simply too complex to lower it further.
