### ISSUE TITLE
Support swiping targets

### ISSUE THREAD

**Issue by StLa1** [KieronQuinn/Smartspacer#75]
### Suggestion

Hello,

First congrats for the very high quality app and the easy set up

However, unless I'm missing something, we either have to choose between huge arrows, or absurdly minuscule dots, which are pretty much impossible to hit

A swipe gesture would make a lot of sense

**Comment by KieronQuinn** [comment]
Not possible with a widget.

**Comment by StLa1** [comment]
Hmm, that sucks

Would it be possible to have a 4th page control option where the arrows are invisible but their touch target still exist?

**Comment by ThatOneCalculator** [comment]
Also, seems that using Smartspacer as Lawnchair's AAG provider instead of as a widget actually supports swiping! 

https://github.com/KieronQuinn/Smartspacer/assets/44733677/19eed98b-5abc-4776-bb7c-0406730c3d0d

**Comment by KieronQuinn** [comment]
> Also, seems that using Smartspacer as Lawnchair's AAG provider instead of as a widget actually supports swiping!
> 
>  VID_20231210_085356_754.mp4

Yes, because Lawnchair implements the Smartspacer client SDK. I did that.

**Comment by ThatOneCalculator** [comment]
Awesome! I was using Lawnchair before, but always just used the widget. Thank you for implementing that!!

**Comment by KieronQuinn** [comment]
> Sorry to come back to this old issue, but I was wanting the same thing. Out of curiosity, is there a specific problem with the Smartspace widget that prevents it from being swiped? I have other widgets on my homescreen that can be scrolled/swiped. Is there a reason Smartspace is different?
> 
> Edit: I'm using Nova Launcher if that makes any difference.

Horizontal scrolling is not supported in widgets. That's the reason.

**Comment by parthmawai** [comment]
> > Sorry to come back to this old issue, but I was wanting the same thing. Out of curiosity, is there a specific problem with the Smartspace widget that prevents it from being swiped? I have other widgets on my homescreen that can be scrolled/swiped. Is there a reason Smartspace is different?
> > 
> > Edit: I'm using Nova Launcher if that makes any difference.
> 
> Horizontal scrolling is not supported in widgets. That's the reason. 

Can vertical scrolling work instead ?? In a way like ios has those stacked widgets .

**Comment by ThatOneCalculator** [comment]
Like this, yeah? I think they meant if it was more vertically paginated (1 swipe = snap to next item)

https://github.com/user-attachments/assets/16f2d4ea-f04b-4559-9a45-e3f27f36b710

**Comment by parthmawai** [comment]
> Like this, yeah? I think they meant if it was more vertically paginated (1 swipe = snap to next item)
> 
> https://github.com/user-attachments/assets/16f2d4ea-f04b-4559-9a45-e3f27f36b710
> 
> 

Yes, like in lawnchair but vertical, with some snap animation instead of just simple scroll animation

**Comment by KieronQuinn** [comment]
Unfortunately snapping is not supported in widgets

**Comment by parthmawai** [comment]
Okay, but there could be a mode where only one target is shown at a time, and can be switched through vertical scrolls, right ?

**Comment by KieronQuinn** [comment]
No, that isn't possible either. The only vertical scrolling supported by widgets is what is there already.
