### ISSUE TITLE
Weather is inaccurate 

### ISSUE THREAD

**Issue by dep** [KieronQuinn/Smartspacer#76]
### Description

The complication temperature says 53 degrees but when I tap it, the Google weather app says it's 37. Where is it getting this temperature from?

**Comment by KieronQuinn** [comment]
The temperature comes from At a Glance. If it's wrong, either the temperature in AAG hasn't updated (which is normal, it doesn't update constantly), or it's stuck, in which case disabling & re-enabling Native Smartspace will fix it.
