### ISSUE TITLE
White square icon for Music target with InnerTune with fallback off

### ISSUE THREAD

**Issue by ThatOneCalculator** [KieronQuinn/Smartspacer#77]
### Description

The Music target shows a white square for InnerTune's logo, despite me having the use notification icon fallback off in the settings. This only occurs with InnerTune, YouTube/SoundCloud/Metro work fine. 

Smartspacer:

![Screenshot_20231210-090604~2](https://github.com/KieronQuinn/Smartspacer/assets/44733677/01784b02-852a-4ab4-8d41-e5093ca37c38)

Notification shade (icon shows fine in top-left):

![Screenshot_20231210-090610~2](https://github.com/KieronQuinn/Smartspacer/assets/44733677/010f2cf9-29b6-4444-9259-408ebb937111)

**Comment by KieronQuinn** [comment]
This is caused by the music app not sending the right data, they're sending the album art as a icon (which is wrong). The next version will ignore the icon because so many are doing this. It's not a Smartspacer bug though.

**Comment by ThatOneCalculator** [comment]
Ah, gotcha. Thank you for the clarification!

**Comment by KieronQuinn** [comment]
> This is caused by the music app not sending the right data, they're sending the album art as a icon (which is wrong). The next version will ignore the icon because so many are doing this. It's not a Smartspacer bug though.

Added in 1.3.2
