### ISSUE TITLE
[Bug] Accessibility Service restricted

### ISSUE THREAD

**Issue by silas229** [KieronQuinn/Smartspacer#8]
### Description

![Screenshot_2023-10-25-11-04-05-90_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/KieronQuinn/Smartspacer/assets/23215125/e78a57e7-afa9-407f-be90-b17327ada42c)

Device Info:
OnePlus Nord 2G
Oxygen OS 13.0 (Android 13)

**Comment by KieronQuinn** [comment]
This isn't a bug, the app tells you how to get around it already. If you ignored that step before getting to this screen, follow Google's official page on it: https://support.google.com/android/answer/12623953?hl=en-GB
