### ISSUE TITLE
[Bug] Smartspacer widget not displaying correctly on KISS Launcher

### ISSUE THREAD

**Issue by Rochey** [KieronQuinn/Smartspacer#83]
### Description

Describe the bug
When adding the Smartspacer widget onto the homescreen of KISS launcher, it is shown with the text cut off and there is no way to make it bigger. The option to "Enlarge" the widget isn't available that KISS normally shows.

To Reproduce

1. Install Smartspacer and set it up
2. Use the "Add widget" option in KISS launcher to add the Smartspacer widget
3. See the issue

Expected behavior
The Smartspacer widget should be shown without the text cut off. The option to "Enlarge" the widget should be available

Screenshots
Screenshots added to show the text being cut off on the widget and the options showing no "Enlarge" option

![Screenshot_20231211-144503](https://github.com/KieronQuinn/Smartspacer/assets/1190108/57ee25dc-e66f-47eb-b8d6-d2cb79b5764e)
![Screenshot_20231211-144449](https://github.com/KieronQuinn/Smartspacer/assets/1190108/60e94f46-985c-47e9-be00-f2fb42113c05)

Additional context
My device is:
Pixel 6
Latest stable Android 14

I had raised this with the developer of the KISS launcher but he said it wasn't a KISS issue and suggested I raise the issue with Smartspacer.  Here is the link to the issue I raised:
[https://github.com/Neamar/KISS/issues/2228](https://github.com/Neamar/KISS/issues/2228)

His response is below:
This is due to Smartspacer widget constraints and cannot be fixed in KISS.
Can you please create bug in their repo for this problem?

See also https://github.com/Neamar/KISS/issues/1871 and https://github.com/Neamar/KISS/pull/1872, size of widgets in KISS can be changed using lines only, where one line has height of 50dp

Smartspacer widget defines [maxResizeHeight="80dp"](https://github.com/KieronQuinn/Smartspacer/blob/a3bd560f0f550b8fcb5ed82081524235eb43e571/app/src/main/res/xml/widget_smartspacer.xml#L8) so we can never increase to height of two lines or 100dp
Though, minimal height of this widget is defined as 10dp, so showing it in KISS with height of 50dp shouldn't be a problem IMO.

**Comment by KieronQuinn** [comment]
It's now 100dp in 1.3.3. Any higher would allow 2 cell height in regular launchers which I'd rather avoid.

**Comment by Rochey** [comment]
Just tried 1.3.3 on KISS launcher and it is working much better. Initially it shows the text cut off but I'm now able to "Enlarge" it and show all the information I need. 
Thanks for making the change.
