### ISSUE TITLE
[Suggestion] requirement for "no other targets or complications" or "only 1 page"

### ISSUE THREAD

**Issue by realmenwearpink2** [KieronQuinn/Smartspacer#84]
### Suggestion

Having the ability to set a target or complication to show ONLY when there is 1 page being displayed.
For example, having my step count show but only when it will be on the first page. If there is information that would push it to the 2nd or 3rd pages, then don't display

**Comment by KieronQuinn** [comment]
This is too complex and would break the logical way that Targets & Complications work, so it's out of scope. Sorry.
