### ISSUE TITLE
[Bug] switching system theme disables Smartspacer

### ISSUE THREAD

**Issue by realmenwearpink2** [KieronQuinn/Smartspacer#87]
### Description

When I toggle system theme between light/dark mode, Smartspacer stops working (only the date is displayed) and doesn't come back until I force stop, causing native smartspace to re-enable itself.

**Comment by KieronQuinn** [comment]
This is a launcher bug, not Smartspacer. It will fix itself when the next target update happens, or the launcher restarts.
