### ISSUE TITLE
[Suggestion] Please add plugins to the Play Store for Google Advanced Protections users

### ISSUE THREAD

**Issue by Cr4z33** [KieronQuinn/Smartspacer#88]
### Suggestion

Being part of those users (https://landing.google.com/advancedprotection/) I am allowed to install APKs from the Google Play Store only. 🥲

Is there any chance you can publish them there please?

In the past I could use LADB to sideload APKs, but now (having an S22 Ultra with Android v14.x) this method cannot be used anymore.

**Comment by KieronQuinn** [comment]
I no longer publish apps like this to the play store due to the risk of association bans, which would risk my day job. Sorry.

**Comment by Cr4z33** [comment]
Oh OK I wasn't aware of that.

I hope then that I can find a working method again in the next future.
