### ISSUE TITLE
Apply new Android pagination animation to pagination dots when used with Lawnchair

### ISSUE THREAD

**Issue by ThatOneCalculator** [KieronQuinn/Smartspacer#90]
### Suggestion

Ref: https://github.com/LawnchairLauncher/lawnchair/issues/3849#issuecomment-1854801752

---

Copied from original issue:

### Describe the feature

Applying this animation:

https://github.com/LawnchairLauncher/lawnchair/assets/44733677/12d763f0-5c8f-4e16-bbb4-81a4789204ff

To these AAG dots:

https://github.com/LawnchairLauncher/lawnchair/assets/44733677/79991d9d-41db-44f8-8d71-3c28c1ccda72

### Why would it be useful to add?

Visual consistency

**Comment by KieronQuinn** [comment]
It mimics the stock At a Glance, which does not do this. The current animation already matches.

**Comment by ThatOneCalculator** [comment]
If anything, I feel like AAG not having that is an issue on Google's side. Both home pages and the notification shade use the new animation.
