### ISSUE TITLE
Add root mode

### ISSUE THREAD

**Issue by StarVase** [KieronQuinn/Smartspacer#91]
### Suggestion

For rooted users, every time start up, showing a notification to launch shizuku is not a pleasant thing. My suggestion is add root mode which don't need shizuku. Auto enable without inquiring users.

**Comment by KieronQuinn** [comment]
Not possible. SystemUI always needs to restart, regardless of root, so it cannot be entirely automated without causing unexpected restarts for the user. There's already a button in the notification to activate it immediately, if you really _really_ want it fully automated and don't care for the interruption, have something click that button automatically.
