### ISSUE TITLE
[Suggestion] Font selection option

### ISSUE THREAD

**Issue by sammukhgupta** [KieronQuinn/Smartspacer#92]
### Suggestion

Hello, currently I am using smartspacer with lawnchair on one UI 6. I am using a custom font via ZFont. The smartspacer widget shows data in Google sans text only and there is no option to change it to system used font. Can you kindly add an option to select custom fonts or to enable system font?

Thanks!
Sammukh

**Comment by KieronQuinn** [comment]
Not possible, widgets can't dynamically change font or else I'd have already implemented it with true Google Sans (rather than relying on the system one)
