### ISSUE TITLE
Widgets don't appear in the Screensaver

### ISSUE THREAD

**Issue by EliasOS** [KieronQuinn/Smartspacer#94]
### Description

I have a problem and I can't get the text of the custom widgets to appear. I have Android 14 based on Evolution X so if anyone has the same problem with an official OS let me know 😓

PS: I recently installed the app and I have only installed extensions without configuring anything.

https://github.com/KieronQuinn/Smartspacer/assets/61661800/40ca66f0-2709-4409-ac3f-4908b7be3d16

**Comment by KieronQuinn** [comment]
Thanks for the video, I've now _finally_ been able to reproduce this by getting the same config of wallpaper colours, so now I can fix it

**Comment by KieronQuinn** [comment]
Fixed in 1.4
