### ISSUE TITLE
[Bug] Smartspacer seems to be not working

### ISSUE THREAD

**Issue by MeguMario** [KieronQuinn/Smartspacer#95]
### Description

I have a non-rooted Pixel 3 running on the latest update available (Android 12 SP1A.210812.016.C2) and Smartspacer doesn't seems to work. As Native Smartspace is apparently not available I decided to use OEM Smartspace but that also didn't work as well. 

![Screenshot_20231217-141135](https://github.com/KieronQuinn/Smartspacer/assets/44724359/22ad965a-8d07-4926-8d65-427a67e49e6c)
[smartspacer_target_dump_2023-12-17T14_23_50.854974.txt](https://github.com/KieronQuinn/Smartspacer/files/13695074/smartspacer_target_dump_2023-12-17T14_23_50.854974.txt)

also with OEM Smartspace, there's this warning, but this can be avoided by quickly turning on Shizuku before Smartspacer start up
![Screenshot_20231217-145029](https://github.com/KieronQuinn/Smartspacer/assets/44724359/dc8cd811-c9a9-44e9-bd52-e9c7c85ebf26)

**Comment by KieronQuinn** [comment]
This isn't a bug, it's not compatible with your device. You will need to use the widget or a launcher with integrated support.
