### ISSUE TITLE
Swipe up to Home locks up the app launched from Expanded Smartspace 

### ISSUE THREAD

**Issue by MeguMario** [KieronQuinn/Smartspacer#96]
### Description

When inside an app launched from Expanded Smartspace, attempting to go back to Home screen by swiping up results in the app locking up and any user interactions are refused (swipe down to open quick settings stills work). In that state, the only way to go back to the home screen is to lock the phone and unlock it.

https://github.com/KieronQuinn/Smartspacer/assets/44724359/2eddf436-77f1-46a0-992f-08cd855d54a8

Return to the home screen by repeatedly swiping back works fine and launching an app from Expanded Smartspace in the lockscreen doesn't have any problem with either the swiping up or swiping back gesture

I'm using a Pixel 4 XL on stock Android 13

**Comment by KieronQuinn** [comment]
Unable to reproduce, and this is not under the control of Smartspacer anyway - once an app is opened, the overlay is gone

**Comment by MeguMario** [comment]
I don't know whether this is the problem with the firmware or Smartspacer, but I think it's something to do with Android 13 firmware(s), as I could reproduce this on my other Pixel 4 XL with LineageOS 20 (though it behaved differently compare to my daily driver), but on my Pixel 6 Pro running on the latest Android 14, i was unable to reproduce the bug as well

This is on the other Pixel 4 XL
https://github.com/KieronQuinn/Smartspacer/assets/44724359/3f2cf766-32ad-4850-add6-3e6b0781f86a

This is on the Pixel 6 Pro
https://github.com/KieronQuinn/Smartspacer/assets/44724359/547811a8-89e9-4351-b821-edbe41942bb0

I won't reopen this issue but if anyone is able to reproduce this then much appreciated.

**Comment by MeguMario** [comment]
I managed to do some additional testing on an emulated Android 13 image, the behavior is indeed the same as the LineageOS sample. Though I noted a difference

- the music app (ViMusic) managed to retain user input though very inconsistence. 

I'm really sorry about the emulated device kept flashing, anytime the systemui crash it goes into that state.

https://github.com/KieronQuinn/Smartspacer/assets/44724359/b42cb488-084a-4782-bcf2-6cfbd1a68051

**Comment by KieronQuinn** [comment]
I can reproduce it with that exact config, but it doesn't seem to be a Smartspacer bug. I have no control over the recents of another app, nor the animation of it closing. It's likely this _was_ an Android bug and was fixed in 14.
