### ISSUE TITLE
[Suggestion] Visualizer for Music

### ISSUE THREAD

**Issue by ThatOneCalculator** [KieronQuinn/Smartspacer#97]
### Suggestion

Having a small visualizer inside the complication for the music target's complication would be a great touch. I'm not sure if you can draw any composable inside there. If so, then a library like [audiofx.Visualizer](https://developer.android.com/reference/android/media/audiofx/Visualizer). If not, a script like [this](https://github.com/ThatOneCalculator/bspwm-dotfiles/blob/main/polybar/scripts/cava.py) could be used to get the output of a visualizer into text.

https://github.com/KieronQuinn/Smartspacer/assets/44733677/f1c623d0-eab6-4f59-b0b5-a76733777c8d

**Comment by KieronQuinn** [comment]
Not possible, it has to fit the template

**Comment by ThatOneCalculator** [comment]
Probably should be closed as not planned, but doesn't the template support text? As suggested in the original issue, there's relatively simple ways to get a headless visualizer to output a text representation.

**Comment by KieronQuinn** [comment]
Not in this way, it would need updates too often. It's like a widget but with more restrictions.

**Comment by ThatOneCalculator** [comment]
Gotcha. Figured I'd put the idea out there. Apologies if some of my ideas are not realistic, as I'm not very well versed in Android development.

**Comment by KieronQuinn** [comment]
I suggest you join the Discord and put them there if you can, saves opening an issue for it to be closed

**Comment by ThatOneCalculator** [comment]
Yep, joined a few minutes ago!
